### ISSUE TITLE
开始搞sdk了嘛。

### ISSUE THREAD

**Issue by mshyh** [wechatpay-apiv3/wechatpay-java#1]
⛽️

**Comment by Eric-Lee-Handyman** [comment]
已经开发了一段时间，初版近期会放出来，看看大家反馈，后续会逐步丰富业务API的接口。

**Comment by mshyh** [comment]
👍

**Comment by songdehuai** [comment]
有大概发布时间吗？

**Comment by xy-peng** [comment]
@songdehuai 目前正在积极开发中。很快会发布一个 Technology Preview。

**Comment by Eric-Lee-Handyman** [comment]
第一个版本已发出来了，当前为开发版本，建议仅用于测试，谨慎用于生产环境。 
有意见欢迎大家提issue~
