### ISSUE TITLE
新发的0.2.4和之前的类和之前没区别呀？

### ISSUE THREAD

**Issue by xingwenkai** [wechatpay-apiv3/wechatpay-java#100]
### 错误描述

0.2.3的类和0.2.4的没有区别呀
![image](https://user-images.githubusercontent.com/61527421/209895124-b2de81a4-017f-4b9d-b5d0-8a6edf47f5c0.png)

### 重现bug的步骤

0.2.3的类和0.2.4的没有区别呀
![image](https://user-images.githubusercontent.com/61527421/209895124-b2de81a4-017f-4b9d-b5d0-8a6edf47f5c0.png)

他的构造方法传参还是和示例不一样
![image](https://user-images.githubusercontent.com/61527421/209895190-7d393a73-9888-4958-b43d-ab78a607f1bc.png)

### 预期行为

希望得到一个正确的参数

### 操作系统

win

### Java 版本

8

### wechatpay-java 版本

0.2.4

**Comment by xy-peng** [comment]
可能是示例有问题。这样，或者用 `RSAAutoCertificateConfig`

```java
NotificationConfig config = new RSAAutoCertificateConfig.Builder()
        .merchantId(merchantId)
        .privateKeyFromPath(privateKeyPath)
        .merchantSerialNumber(merchantSerialNumber)
        .apiV3Key(apiV3key)
        .build();

// 初始化 NotificationParser
NotificationParser parser = new NotificationParser(config);
```

**Comment by xingwenkai** [comment]
那这样我的config就不是全局的了，我定义多个config，会出现错误吗
![image](https://user-images.githubusercontent.com/61527421/209895745-ed5331c9-fbc3-4d0c-ae98-e05024f3d1b2.png)

**Comment by xingwenkai** [comment]
我强制转换可以吗？
@xy-peng 

![image](https://user-images.githubusercontent.com/61527421/209895940-dac63b71-554a-4071-a8fb-72d0eb44430c.png)

**Comment by xy-peng** [comment]
因为你两个场景都要用，建议持有 `RSAAutoCertificateConfig`，别用 Config 或者 NotificationConfig。

我也看看文档怎么引导。
