### ISSUE TITLE
微信

### ISSUE THREAD

**Issue by twoyearsold** [wechatpay-apiv3/wechatpay-java#102]
### 错误描述

我想问下解密器应该如何使用

### 重现bug的步骤

测试案例NotificationParserTest testParse这个方法
NotificationParser parser = new NotificationParser(verifiers, ciphers); 后如何实现解密微信通知的内容 还是没这个功能

### 预期行为

https://pay.weixin.qq.com/wiki/doc/apiv3/apis/chapter3_5_5.shtml 
商户对resource对象进行解密后，得到的资源对象示例

### 操作系统

windows11

### Java 版本

java8

### wechatpay-java 版本

v0.2.4

**Comment by twoyearsold** [comment]
使用文档的话 构建的config Cannot resolve constructor 'NotificationParser(com.wechat.pay.java.core.Config)'

**Comment by xy-peng** [comment]
不好意思，文档示例有问题，正在考虑如何修改。`RSAAutoCertificateConfig` 的示例如果用在回调场景，要使用 `NotificationConfig`

```java
// 如果已经初始化了 RSAAutoCertificateConfig，可直接使用
// 没有的话，则构造一个
NotificationConfig config = new RSAAutoCertificateConfig.Builder()
        .merchantId(merchantId)
        .privateKeyFromPath(privateKeyPath)
        .merchantSerialNumber(merchantSerialNumber)
        .apiV3Key(apiV3key)
        .build();

// 初始化 NotificationParser
NotificationParser parser = new NotificationParser(config);
```

**Comment by twoyearsold** [comment]
你这个代码执行不通类型无法转换
应该是
 NotificationConfig notification =new RSANotificationConfig.Builder()
						.apiV3Key(apiV3key)
						.certificates(certKey)
						.build());
NotificationParser parser = new NotificationParser(config);
然后又出现这个问题 
com.wechat.pay.java.core.exception.ValidationException: Processing WechatPay notification,signature verification failed,

**Comment by twoyearsold** [comment]
public boolean verify(String serialNumber, String message, String signature) {
    X509Certificate certificate = certificateProvider.getCertificate(serialNumber);
    if (certificate == null) {
      logger.error(
          "Verify the signature and get the WechatPay certificate corresponding to "
              + "serialNumber[{}] is empty.",
          serialNumber);
      return false;
    }
    return verify(certificate, message, signature);
  }
com.wechat.pay.java.core.cipher.AbstractVerifier 这玩意出的 错
  是缺少什么步骤吗

**Comment by twoyearsold** [comment]
public static final Map<String, NotificationConfig> NotificationConfigCach = new ConcurrentHashMap<>();


	@Override
	public Boolean isPaysuccess(String notificationJson, HttpServletRequest request) throws IOException {
		//微信传递过来的签名
		String signature = request.getHeader("Wechatpay-Signature");
		//随机串
		String nonce = request.getHeader("Wechatpay-Nonce");
		//时间戳
		String timstamp = request.getHeader("Wechatpay-Timestamp");
		//证书序列号（微信平台）
		String wechatPayCertificateSerialNumber = request.getHeader("Wechatpay-Serial");
		//签名类型
		String signatureType = request.getHeader("Wechatpay-Signature-Type");
		// 构造 RequestParam
		RequestParam requestParam = new RequestParam.Builder()
				.serialNumber(wechatPayCertificateSerialNumber)
				.nonce(nonce)
				.signature(signature)
				.timestamp(timstamp)
// 若未设置signType，默认值为 WECHATPAY2-SHA256-RSA2048
				.signType(signatureType)
				.body(notificationJson)
				.build();

		PayChannel channel = getPayChannel();
		NotificationConfig notificationConfig = getNotificationConfig(channel.getChannelMchId());
		NotificationParser parser = new NotificationParser(notificationConfig);

		Transaction decryptObject = parser.parse(requestParam,Transaction.class);


		return  true;

	}




	private PayChannel getPayChannel() {

		return payCach.computeIfAbsent(PayChannelNameEnum.WEIXIN_MIN.getName(), c ->
		channelService.getOne(
				Wrappers.<PayChannel>lambdaQuery().eq(PayChannel::getChannelId, PayChannelNameEnum.WEIXIN_MIN),
				false));

	}

	
	private NotificationConfig   getNotificationConfig(String merchantId) throws IOException {
		String certKey  =  IOUtil.loadStringFromPath(certKeyPath);
		return NotificationConfigCach.computeIfAbsent(merchantId, c ->
				new RSANotificationConfig.Builder()
						.apiV3Key(apiV3key)
						.certificates(certKey)
						.build());


	}


总代码 是这样

**Comment by twoyearsold** [comment]
问题解决了  .certificates(certKey) 应该用的是 CertificateDownloader-1.2.0-jar-with-dependencies.jar 这个生成的pem 而不是apiclient_cert.pem
