### ISSUE TITLE
没有微信分账吗 是否可以支持微信分账呢

### ISSUE THREAD

**Issue by nginx-1** [wechatpay-apiv3/wechatpay-java#103]

**Comment by Error-NotFound** [comment]
同求

**Comment by Error-NotFound** [comment]
`public class WxProfitsharingService {
    private final HttpClient httpClient;
    private final HostName hostName;

    public WxProfitsharingService(HttpClient httpClient, HostName hostName) {
        this.httpClient = requireNonNull(httpClient);
        this.hostName = hostName;
    }
    /** WxProfitsharingService构造器 */
    public static class Builder {

        private HttpClient httpClient;
        private HostName hostName;
        /**
         * 设置请求配置，以该配置构造默认的httpClient，若未调用httpClient()方法，则必须调用该方法
         *
         * @param config 请求配置
         * @return Builder
         */
        public Builder config(Config config) {
            this.httpClient =
                    new DefaultHttpClientBuilder()
                            .credential(requireNonNull(config.createCredential()))
                            .validator(requireNonNull(config.createValidator()))
                            .build();
            return this;
        }
        /**
         * 设置微信支付域名，可选，默认为api.mch.weixin.qq.com
         *
         * @param hostName 微信支付域名
         * @return Builder
         */
        public Builder hostName(HostName hostName) {
            this.hostName = hostName;
            return this;
        }
        /**
         * 设置自定义httpClient，若未调用config()，则必须调用该方法
         *
         * @param httpClient httpClient
         * @return Builder
         */
        public Builder httpClient(HttpClient httpClient) {
            this.httpClient = httpClient;
            return this;
        }
        /**
         * 构造服务
         *
         * @return WxProfitsharingService
         */
        public WxProfitsharingService build() {
            return new WxProfitsharingService(httpClient, hostName);
        }
    }

    /**
     * 请求分账
     *
     * @param request 请求参数
     * @throws HttpException 发送HTTP请求失败。例如构建请求参数失败、发送请求失败、I/O错误等。包含请求信息。
     * @throws ValidationException 发送HTTP请求成功，验证微信支付返回签名失败。
     * @throws ServiceException 发送HTTP请求成功，服务返回异常。例如返回状态码小于200或大于等于300。
     * @throws MalformedMessageException 服务返回成功，content-type不为application/json、解析返回体失败。
     */
    public ProfitsharingResponse profitsharingOrder(ProfitsharingRequest request) {
        String requestPath =
                "https://api.mch.weixin.qq.com/v3/profitsharing/orders";
        ProfitsharingRequest realRequest = request;
        if (this.hostName != null) {
            requestPath = requestPath.replaceFirst(HostName.API.getValue(), hostName.getValue());
        }
        HttpHeaders headers = new HttpHeaders();
        headers.addHeader(Constant.ACCEPT, MediaType.APPLICATION_JSON.getValue());
        headers.addHeader(Constant.CONTENT_TYPE, MediaType.APPLICATION_JSON.getValue());
        HttpRequest httpRequest =
                new HttpRequest.Builder()
                        .httpMethod(HttpMethod.POST)
                        .url(requestPath)
                        .headers(headers)
                        .body(createRequestBody(realRequest))
                        .build();
        HttpResponse<ProfitsharingResponse> httpResponse =
                httpClient.execute(httpRequest, ProfitsharingResponse.class);
        return httpResponse.getServiceResponse();
    }

    private RequestBody createRequestBody(Object request) {
        return new JsonRequestBody.Builder().body(toJson(request)).build();
    }

    public static class ProfitsharingRequest{
        @SerializedName("appid")
        private String appid;
        @SerializedName("transaction_id")
        private String transactionId;
        @SerializedName("out_order_no")
        private String outOrderNo;
        @SerializedName("receivers")
        private List<Receiver> receivers;
        @SerializedName("unfreeze_unsplit")
        private boolean unfreezeUnsplit;

        public String getAppid() {
            return appid;
        }

        public void setAppid(String appid) {
            this.appid = appid;
        }

        public String getTransactionId() {
            return transactionId;
        }

        public void setTransactionId(String transactionId) {
            this.transactionId = transactionId;
        }

        public String getOutOrderNo() {
            return outOrderNo;
        }

        public void setOutOrderNo(String outOrderNo) {
            this.outOrderNo = outOrderNo;
        }

        public List<Receiver> getReceivers() {
            return receivers;
        }

        public void setReceivers(List<Receiver> receivers) {
            this.receivers = receivers;
        }

        public boolean isUnfreezeUnsplit() {
            return unfreezeUnsplit;
        }

        public void setUnfreezeUnsplit(boolean unfreezeUnsplit) {
            this.unfreezeUnsplit = unfreezeUnsplit;
        }

        @Override
        public String toString() {
            return "ProfitsharingRequest{" +
                    "appid='" + appid + '\'' +
                    ", transactionId='" + transactionId + '\'' +
                    ", outOrderNo='" + outOrderNo + '\'' +
                    ", receivers=" + receivers +
                    ", unfreezeUnsplit=" + unfreezeUnsplit +
                    '}';
        }
    }
    public class ProfitsharingResponse{
        @SerializedName("transaction_id")
        private String transactionId;
        @SerializedName("out_order_no")
        private String outOrderNo;
        @SerializedName("order_id")
        private String orderId;
        @SerializedName("state")
        private String state;
        @SerializedName("receivers")
        private List<Receiver> receivers;
    }
    public static class Receiver{
        @SerializedName("type")
        private String type;
        @SerializedName("account")
        private String account;
        @SerializedName("name")
        private String name;
        @SerializedName("amount")
        private int amount;
        @SerializedName("description")
        private String description;

        public String getType() {
            return type;
        }

        public void setType(String type) {
            this.type = type;
        }

        public String getAccount() {
            return account;
        }

        public void setAccount(String account) {
            this.account = account;
        }

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }

        public int getAmount() {
            return amount;
        }

        public void setAmount(int amount) {
            this.amount = amount;
        }

        public String getDescription() {
            return description;
        }

        public void setDescription(String description) {
            this.description = description;
        }

        @Override
        public String toString() {
            return "Receiver{" +
                    "type='" + type + '\'' +
                    ", account='" + account + '\'' +
                    ", name='" + name + '\'' +
                    ", amount='" + amount + '\'' +
                    ", description='" + description + '\'' +
                    '}';
        }
    }
}`
