### ISSUE TITLE
支付回调解析通知有bugNotificationParser

### ISSUE THREAD

**Issue by 7019492** [wechatpay-apiv3/wechatpay-java#105]
### 错误描述

NotificationParser 不能使用RSAAutoCertificateConfig 只能用NotificationConfig  而NotificationConfig和Config接口又是两个不相关的

### 重现bug的步骤

调完微信支付后，回调接口

### 预期行为

统一一下config

### 操作系统

Windows

### Java 版本

java 8

### wechatpay-java 版本

0.2.3

**Comment by xy-peng** [comment]
请使用 0.2.4 版本
