### ISSUE TITLE
建议返回的类名字差异化，无法在同一个类中使用不用支付方式的返回类

### ISSUE THREAD

**Issue by deyun93** [wechatpay-apiv3/wechatpay-java#107]
### 您的功能请求与问题有关吗？ 请描述您遇到的问题

比如jsapi和app支付返回类名字都用的是PrepayWithRequestPaymentResponse，虽然有可行方案，但是对开发来说不简便

**Comment by xy-peng** [comment]
我们考虑过使用不同的命名，比如 `JsapiPrepayWithRequestPaymentResponse`。前缀跟命名空间就重复了。

最后的决定基于我们调研，大部分开发者说不同的支付方式的实现是分项目的，在同一个类中很少出现不同的支付方式。所以，最后的决定是通过命名空间来区分，不添加前缀。

@deyun93 你说的“可行方案”是什么？不简便能具体说说吗，使用IDE的智能补全遇到了困难。是因为太长了，所以看不到完整的命名空间？

**Comment by deyun93** [comment]
> 我们考虑过使用不同的命名，比如 `JsapiPrepayWithRequestPaymentResponse`。前缀跟命名空间就重复了。
> 
> 最后的决定基于我们调研，大部分开发者说不同的支付方式的实现是分项目的，在同一个类中很少出现不同的支付方式。所以，最后的决定是通过命名空间来区分，不添加前缀。
> 
> @deyun93 你说的“可行方案”是什么？不简便能具体说说吗，使用IDE的智能补全遇到了困难。是因为太长了，所以看不到完整的命名空间？

现目前因为是小项目，没办法分项目，不然又得开一个docker，没必要。我目前用的方式是把controller和service分开。下一步我想自定义反回接口，少写几个controller。
