### ISSUE TITLE
服务商无法使用RSAAutoCertificateConfig

### ISSUE THREAD

**Issue by taolive** [wechatpay-apiv3/wechatpay-java#108]
### 错误描述

服务商实例化config对象时，提示Invalid AES key length: 33 bytes

### 重现bug的步骤

```java

 config =
            new RSAAutoCertificateConfig.Builder()
                .merchantId(merchantId)
                .privateKeyFromPath(path)
                .merchantSerialNumber(merchantSerialNumber)
                .apiV3Key(apiV3Key)
                .build();
```
会提示
java.lang.IllegalArgumentException: java.security.InvalidKeyException: Invalid AES key length: 33 bytes

	at com.wechat.pay.java.core.cipher.AbstractAeadCipher.decrypt(AbstractAeadCipher.java:83)
	at com.wechat.pay.java.core.certificate.AbstractAutoCertificateProvider.updateCertificate(AbstractAutoCertificateProvider.java:150)
	at com.wechat.pay.java.core.certificate.AbstractAutoCertificateProvider.downloadAndUpdate(AbstractAutoCertificateProvider.java:95)
	at com.wechat.pay.java.core.certificate.AbstractAutoCertificateProvider.<init>(AbstractAutoCertificateProvider.java:76) 
异常信息

### 预期行为

正常调用

### 导致错误的代码片段

```Java
config =
            new RSAAutoCertificateConfig.Builder()
                .merchantId(merchantId)
                .privateKeyFromPath(path)
                .merchantSerialNumber(merchantSerialNumber)
                .apiV3Key(apiV3Key)
                .build();
```

### 操作系统

macOs

### Java 版本

java 17

### wechatpay-java 版本

v0.2.4

### 其他信息

无

**Comment by xy-peng** [comment]
> Invalid AES key length: 33 bytes

APIv3 Key 只有32个字节，你大概率是设置了错误的APIv3Key。

**Comment by taolive** [comment]
config =
            new RSAAutoCertificateConfig.Builder()
                .merchantId(merchantId) // 服务商平台中的商户号
                .privateKeyFromPath(path)
                .merchantSerialNumber(merchantSerialNumber) // 对应证书序列号
                .apiV3Key(apiV3Key)  // v3 秘钥
                .build();
