### ISSUE TITLE
你好，请问这个api有计算签名的方法吗

### ISSUE THREAD

**Issue by xingwenkai** [wechatpay-apiv3/wechatpay-java#109]
### 您的功能请求与问题有关吗？ 请描述您遇到的问题

你好，请问这个api有计算签名的方法吗
![image](https://user-images.githubusercontent.com/61527421/210323063-f2aa25d9-dcbf-48c5-8c4b-983afdfbcbae.png)

**Comment by xingwenkai** [comment]
如果不需要自己计算签名，那么服务端调用JSAPI下单后获取到prepay_id，小程序调起微信支付不是需要签名吗，这个签名如果不需要计算，那么需要怎么调用api实现调起支付呢

**Comment by xingwenkai** [comment]
有没有一个计算签名的示例呀 @xy-peng

**Comment by xy-peng** [comment]
> 如果不需要自己计算签名，那么服务端调用JSAPI下单后获取到prepay_id，小程序调起微信支付不是需要签名吗，这个签名如果不需要计算，那么需要怎么调用api实现调起支付呢

我们提供了方法。以 JSAPI 为例，`JsapiServiceExtension.PrepayWithRequestPaymentResponse()` 直接预下单并生成了调起支付的所有参数。

如果你还是要自己实现，计算签名可参考 [JsapiServiceExtension](https://github.com/wechatpay-apiv3/wechatpay-java/blob/968a2ff8fb35c808f82827342abb100e30691a98/service/src/main/java/com/wechat/pay/java/service/payments/jsapi/JsapiServiceExtension.java#L59)。
