### ISSUE TITLE
RSAAutoCertificateConfig  为什么不支持多个呢，一个商户号被多个项目怎么办，就必须手动或自己写脚本更新证书吗

### ISSUE THREAD

**Issue by mumudm** [wechatpay-apiv3/wechatpay-java#110]

**Comment by xy-peng** [comment]
是指一个项目，会依赖多个子项目的情况吗？然后每个子项目都需要使用 Config ？

**Comment by mumudm** [comment]
是多个项目分别部署，每个项目都要使用 config

**Comment by xy-peng** [comment]
> 是多个项目分别部署，每个项目都要使用 config

不同的项目分别部署，每个独立部署的项目是可以有自己的 `RSAAutoCertificateConfig`的。在一个运行的服务中，每个商户号只能有一个 `RSAAutoCertificateConfig` 实例。
