### ISSUE TITLE
退款以及账单下载的功能大概会在哪个版本实现啊

### ISSUE THREAD

**Issue by mzbxky** [wechatpay-apiv3/wechatpay-java#111]

**Comment by xy-peng** [comment]
境内商户的退款已经支持了，可参考[RefundService](https://github.com/wechatpay-apiv3/wechatpay-java/blob/main/service/src/main/java/com/wechat/pay/java/service/refund/RefundService.java)。

下载账单暂时只支持裸的下载接口，可参考相关[单元测试代码](https://github.com/wechatpay-apiv3/wechatpay-java/blob/main/core/src/test/java/com/wechat/pay/java/core/http/HttpClientTest.java#L211)。
