### ISSUE TITLE
我想问一下那个直连商户下载账单在那个单元测试里面是哪个啊，没太看懂，不知道哪个

### ISSUE THREAD

**Issue by mzbxky** [wechatpay-apiv3/wechatpay-java#116]

**Comment by xy-peng** [comment]
之前的文档中已经简单补充了一部分 [证书下载](https://github.com/wechatpay-apiv3/wechatpay-java#%E4%B8%8B%E8%BD%BD%E8%B4%A6%E5%8D%95)。你可以先看看。

稍晚点会提供一个更完整的示例。
