### ISSUE TITLE
出个.net的v3 SDK吧

### ISSUE THREAD

**Issue by 980545410** [wechatpay-apiv3/wechatpay-java#117]
### 错误描述

出个.net的v3 SDK吧

### 重现bug的步骤

出个.net的v3 SDK吧

### 预期行为

出个.net的v3 SDK吧

### 导致错误的代码片段

```Java
出个.net的v3 SDK吧
```

### 操作系统

windows

### Java 版本

.net code 6.0

### wechatpay-java 版本

1

### 其他信息

出个.net的v3 SDK吧

**Comment by xy-peng** [comment]
对于.NET SDK 你有什么期望和需求吗？ @980545410 

一般情况下，现阶段建议用第三方的开源.NET SDK。推荐 [Senparc.Weixin —— 微信 .NET SDK](https://github.com/JeffreySu/WeiXinMPSDK) 和 [SKIT.FlurlHttpClient.Wechat](https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat)。

**Comment by 980545410** [comment]
你们出个.net标准 nuget库，.net 用户对接起来安心啊
用第三方的哪有你们出标准的稳定以及速度快呢
不管是加密方式改变，或是接口属性字段改变，你们可以第一时间修改并发布，.net 用户 直接更新nuget ，这样只要我们定期检查，一直可以使用最新的

现在我实现 微信支付 v3 版本，得先定义一堆请求属性与响应属性，然后在自己封装请求数据，在定义一些API的实现方法，繁琐至极，后面但凡你们有改动，.net 用户还得改代码

隔壁支付宝就出了个【简易支付sdk】也是发布了nuget， 简化了一些不必要的字段属性方法，不需要自己创建响应与请求属性，人家已经在库里都定义好，我们用户只需要传参，调用方法，简单解析返回结果即可

**Comment by w8w8w8** [comment]
为啥不出.NET版本的SDK？
