### ISSUE TITLE
支付结果通知验签失败(自动下载平台证书)

### ISSUE THREAD

**Issue by ailefei** [wechatpay-apiv3/wechatpay-java#120]
### 错误描述

问题描述:
使用RSAAutoCertificateConfig配置类生成支付单并成功支付后,支付结果通知验签失败.

错误信息:
`[Request processing failed; nested exception is com.wechat.pay.java.core.exception.ValidationException: Processing WechatPay notification,signature verification failed`

文档中说大部分都是因为序列化了body导致验签失败,但我获取body的方式如下:
` String body = request.getReader().lines().collect(Collectors.joining());`

### 重现bug的步骤

微信JSAPI下单
支付
收到支付结果通知

### 预期行为

成功获取支付结果信息

### 导致错误的代码片段

```Java
public class WxPayService {

    public static String merchantId = "***";
    public static String privateKeyPath = "cert/apiclient_key.pem";
    public static PrivateKey privateFile;
    public static String merchantSerialNumber = "***";
    public static String apiV3key = "***";

    private static RSAAutoCertificateConfig notificationConfig;

    @Autowired
    CustomConfig customConfig;

    static {
        try {
            Resource resource = new ClassPathResource(privateKeyPath);
            InputStream inputStream = resource.getInputStream();
            StringBuilder sb = new StringBuilder();
            String line;
            BufferedReader br = new BufferedReader(new InputStreamReader(inputStream));
            while ((line = br.readLine()) != null) {
                sb.append(line);
            }
            privateFile = PemUtil.loadPrivateKeyFromString(sb.toString());
        } catch (Exception ex) {
            log.error("get resource file error!", ex);
        }
        notificationConfig = new RSAAutoCertificateConfig.Builder()
                .merchantId(merchantId)
                .privateKey(privateFile)
                .merchantSerialNumber(merchantSerialNumber)
                .apiV3Key(apiV3key)
                .build();
    }

    

    @SneakyThrows
    public static Transaction getPayNotify(HttpServletRequest request, String body) {
        String signature = request.getHeader(WECHAT_PAY_SIGNATURE);
        String timestamp = request.getHeader(WECHAT_PAY_TIMESTAMP);
        String nonce = request.getHeader(WECHAT_PAY_NONCE);
        RequestParam requestParam = new RequestParam.Builder()
                .serialNumber(merchantSerialNumber)
                .nonce(nonce)
                .signature(signature)
                .timestamp(timestamp)
                //若未设置signType，默认值为 WECHATPAY2-SHA256-RSA2048
                //.signType(signType)
                .body(body)
                .build();
        // 初始化 NotificationParser
        NotificationParser parser = new NotificationParser(notificationConfig);
        // 验签并解密报文
        Transaction transaction = parser.parse(requestParam, Transaction.class);
        return transaction;
    }
}
```

### 操作系统

Linux

### Java 版本

Java 8

### wechatpay-java 版本

v0.2.5

**Comment by xy-peng** [comment]
你好，可参考下这个 [案例](https://github.com/wechatpay-apiv3/wechatpay-apache-httpclient/issues/152)

**Comment by ailefei** [comment]
@xy-peng 看了案例，是说获取body这里不能用`BufferedReader`吗？
我把获取body的方法从`request.getReader().lines().collect(Collectors.joining())`
修改为了```
StringBuilder sb = new StringBuilder();
        try (ServletInputStream inputStream = request.getInputStream();
             BufferedReader reader = new BufferedReader(new InputStreamReader(inputStream));
        ) {
            String line;

            while ((line = reader.readLine()) != null) {
                sb.append(line);
            }
        }
        String body = sb.toString();
```
但还是验签失败

日志里有这么一句，看起来是没有获取到平台证书：
`ERROR c.w.p.j.core.cipher.AbstractVerifier 54 - Verify the signature and get the WechatPay certificate corresponding to serialNumber[1521D00F99F5FFF7AF3006B1BE6CEC7AF25947A6] is empty.`

**Comment by ailefei** [comment]
@xy-peng 
是说获取body这里换行的问题吗？我把获取body的方法从
`String body = request.getReader().lines().collect(Collectors.joining());`
替换成了但还是不行
`String body;
        try (ServletInputStream inputStream = request.getInputStream()
        ) {
            ByteArrayOutputStream result = new ByteArrayOutputStream();
            byte[] buffer = new byte[1024];
            for (int length; (length = inputStream.read(buffer)) != -1; ) {
                result.write(buffer, 0, length);
            }
            body = result.toString();
        }`

**Comment by xy-peng** [comment]
出错的日志能提供一下吗？

**Comment by ailefei** [comment]
我把日志的商户id和商户证书序列号加了*，看日志问题是没有找到证书文件。这句 Verify the signature and get the WechatPay certificate corresponding to serialNumber[1521D00F99F5FFF7AF3006B1BE6****] is empty

`2023-01-12 14:10:42,480 [pool-2-thread-1] INFO  c.w.p.j.c.c.AbstractAutoCertificateProvider 79 - Begin update Certificates.merchantId:16357***,total updates:3
2023-01-12 14:10:42,716 [pool-2-thread-1] INFO  c.w.p.j.c.c.AbstractAutoCertificateProvider 82 - Finish update Certificates.merchantId:16357***,total updates:4
2023-01-12 14:15:10,779 [http-nio-8088-exec-6] INFO  c.jieworui.api.service.WxPayService 154 - wxPay.notify body:{"id":"c5251a21-802b-5464-98eb-531229b6b7ff","create_time":"2023-01-12T11:11:07+08:00","resource_type":"encrypt-resource","event_type":"TRANSACTION.SUCCESS","summary":"","resource":{"original_type":"transaction","algorithm":"AEAD_AES_256_GCM","ciphertext":"fd7l49JJG/9ciLThxrLAQpRhZccxGQfTmnVh67GvW4rj/8Fd9epZTvY/8VFWs2PAPFF
htNRrSHk01mMMw2HJ8+YCOYQJQPsp+dedcjZNoKVf4g3SKBAplftqd9ifHXx5o5q+Ryfwxz62U64WuDGsu+Qcggprb3G5odJ2dZxhZsxeD0os3o9isEtevb6V5SYi5aTAuRurRlcQm2QDRGlCc8LLiNNxTCYp5BK8TxqNN/9IlD/lnDP4I9ElK/YRONvEstEhXOUmZGe2n/w30A6nrlRCsaDdt8RptdnMUi7aIer5wJ7239wj2qf+8/T0ThYSN9QecyLXIA26S9+7zWZMO00DXpHtc04J80pOds+fhX2LQ9gvDwDgtW7qSM4kkRy5DHkfqVYtdMUMDqqVCXvIlcN1PpG5rWCYD5sP/5qdHXEqJE5NhmQDEknsI25KsC2/Hs6NDtoI2HrrOxz3mlrxQe6qteMY7/ihwFze4dlMou6h2lELHgCIkOvdRQQ2L24epMnlmtYr9LkG4M78eOWuogXyrqQWn7CJjmezvWKoL6o2TNNbTwnaT/MWF88rsx6E=","associated_data":"transaction","nonce":"d3OrJ3PQoz1l"}}
2023-01-12 14:15:10,779 [http-nio-8088-exec-6] ERROR c.w.p.j.core.cipher.AbstractVerifier 54 - Verify the signature and get the WechatPay certificate corresponding to serialNumber[1521D00F99F5FFF7AF3006B1BE6****] is empty.
2023-01-12 14:15:10,780 [http-nio-8088-exec-6] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] 175 - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.wechat.pay.java.core.exception.ValidationException: Processing WechatPay notification,signature verification failed,signType[WECHATPAY2-SHA256-RSA2048]    serial[1521D00F99F5FFF7AF3006B1BE6****]        message[1673504110
T2pR01Vqo7FrvdsaauAaSRW6MZwVfgUZ
{"id":"c5251a21-802b-5464-98eb-531229b6b7ff","create_time":"2023-01-12T11:11:07+08:00","resource_type":"encrypt-resource","event_type":"TRANSACTION.SUCCESS","summary":"","resource":{"original_type":"transaction","aa
lgorithm":"AEAD_AES_256_GCM","ciphertext":"fd7l49JJG/9ciLThxrLAQpRhZccxGQfTmnVh67GvW4rj/8Fd9epZTvY/8VFWs2PAPFhtNRrSHk01mMMw2HJ8+YCOYQJQPsp+dedcjZNoKVf4g3SKBAplftqd9ifHXx5o5q+Ryfwxz62U64WuDGsu+Qcggprb3G5odJ2dZxhZsxeD0os3o9isEtevb6V5SYi5aTAuRurRlcQm2QDRGlCc8LLiNNxTCYp5BK8TxqNN/9IlD/lnDP4I9ElK/YRONvEstEhXOUmZGe2n/w30A6nrlRCsaDdt8RptdnMUi7aIer5wJ7239wj2qf+8/T0ThYSN9QecyLXIA26S9+7zWZMO00DXpHtc04J80pOds+fhX2LQ9gvDwDgtW7qSM4kkRy5DHkfqVYtdMUMDqqVCXvIlcN1PpG5rWCYD5sP/5qdHXEqJE5NhmQDEknsI25KsC2/Hs6NDtoI2HrrOxz3mlrxQe6qteMY7/ihwFze4dlMou6h2lELHgCIkOvdRQQ2L24epMnlmtYr9LkG4M78eOWuogXyrqQWn7CJjmezvWKoL6o2TNNbTwnaT/MWF88rsx6E=","associated_data":"transaction","nonce":"d3OrJ3PQoz1l"}}`

**Comment by xy-peng** [comment]
知道错误了

```java
    @SneakyThrows
    public static Transaction getPayNotify(HttpServletRequest request, String body) {
        String signature = request.getHeader(WECHAT_PAY_SIGNATURE);
        String timestamp = request.getHeader(WECHAT_PAY_TIMESTAMP);
        String nonce = request.getHeader(WECHAT_PAY_NONCE);
        RequestParam requestParam = new RequestParam.Builder()
                .serialNumber(merchantSerialNumber)      <-- 这里要用回调 HTTP 头中的微信支付平台证书序列号，不是商户证书序列号
                .nonce(nonce)
                .signature(signature)
                .timestamp(timestamp)
                //若未设置signType，默认值为 WECHATPAY2-SHA256-RSA2048
                //.signType(signType)
                .body(body)
                .build();
        // 初始化 NotificationParser
        NotificationParser parser = new NotificationParser(notificationConfig);
        // 验签并解密报文
        Transaction transaction = parser.parse(requestParam, Transaction.class);
        return transaction;
    }
```

**Comment by xy-peng** [comment]
你是想用在敏感信息加解密的场景吗？

`Config` 通过 `createEncryptor` 获取 `PrivacyEncryptor`，`PrivacyEncryptor` 有方法 `getWechatpaySerial` 。

谢谢你的问题，我把这一点补充到文档吧。

**Comment by ailefei** [comment]
是的，问题都解决了。再次感谢大佬！🙏

**Comment by rocwang02** [comment]
关于 Body 补充一下: 
`public String nativeNotify(HttpServletRequest request, @RequestBody String requestBody,  
                           HttpServletResponse response) {  
    log.info("# 【微信支付V3】支付成功-回调，通知参数:{} #", response);
.....
}`
对比
`
@ApiOperation("微信支付V3 -> 回调 Native")  
@PostMapping(value = "/native/notify")  
public String nativeNotify(HttpServletRequest request, HttpServletResponse response) {  
    //获取body  
    String body = HttpUtils.readData(request);  
    log.info("# 【微信支付V3】支付成功-回调，通知Body:{} #", body);
.....
}
`
说明: `@RequestBody` 获取的 body 和 `request` 中的 body 字段顺序不一致. 会导致验签 失败!

**Comment by catch6** [comment]
> ```java
> HttpUtils.readData(request)
> ```

你好，可以提供下HttpUtils这个工具类吗

**Comment by zbz0425** [comment]
> 修改后现在是这样 public class HttpUtils {
> 
> ```
> public static byte[] getRawRequestBodyBytes(HttpServletRequest request) throws IOException {
>     ServletInputStream input = request.getInputStream();
>     BufferedInputStream bis = new BufferedInputStream(input);
>     byte[] cache = new byte[1024];
>     int n = 0;
>     ByteArrayOutputStream baos = new ByteArrayOutputStream();
>     while (-1 != (n = bis.read(cache))) {
>         baos.write(cache, 0, n);
>         if (n >= 1 && cache[n - 1] == '}') {
>             break;
>         }
>     }
>     return baos.toByteArray();
> }
> 
> public static String getRawRequestBody(HttpServletRequest request) throws IOException {
>     byte[] bytes = getRawRequestBodyBytes(request);
>     return new String(bytes, StandardCharsets.UTF_8);
> }
> ```
> 
> }
修改后现在是这样
public class HttpUtils {

public static byte[] getRawRequestBodyBytes(HttpServletRequest request) throws IOException {
    ServletInputStream input = request.getInputStream();
    BufferedInputStream bis = new BufferedInputStream(input);
    byte[] cache = new byte[1024];
    int n = 0;
    ByteArrayOutputStream baos = new ByteArrayOutputStream();
    while (-1 != (n = bis.read(cache))) {
        baos.write(cache, 0, n);
        if (n >= 1 && cache[n - 1] == '}') {
            break;
        }
    }
    return baos.toByteArray();
}

public static String getRawRequestBody(HttpServletRequest request) throws IOException {
    byte[] bytes = getRawRequestBodyBytes(request);
    return new String(bytes, StandardCharsets.UTF_8);
}
}


我是修改成这样，从HttpServletRequest读取json就验签成功了，

另外如果json的 } 后面如果还支持有空格

可以 

public class HttpUtils {

    public static byte[] getRawRequestBodyBytes(HttpServletRequest request) throws IOException {
        ServletInputStream input = request.getInputStream();
        BufferedInputStream bis = new BufferedInputStream(input);
        byte[] cache = new byte[1024];
        int n = 0;
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        while (-1 != (n = bis.read(cache))) {
            baos.write(cache, 0, n);
            if (n >= 1 && cache[n - 1] == '}') {
                bis.mark(1); // 标记当前位置
                try {
                    do {
                        n = bis.read(cache);
                        if (n == -1) {
                            break;
                        }
                    } while (Character.isWhitespace(cache[0]));
                    if (n != -1) {
                        continue;
                    }
                } catch (IOException e) {
                    bis.reset();
                }
                break;
            }
        }
        return baos.toByteArray();
    }

    public static String getRawRequestBody(HttpServletRequest request) throws IOException {
        byte[] bytes = getRawRequestBodyBytes(request);
        return new String(bytes, StandardCharsets.UTF_8);
    }

}

**Comment by zbz0425** [comment]
> > ```java
> > HttpUtils.readData(request)
> > ```
> 
> @rocwang02 你好，可以提供下HttpUtils这个工具类吗


修改后现在是这样 public class HttpUtils {

public static byte[] getRawRequestBodyBytes(HttpServletRequest request) throws IOException {
    ServletInputStream input = request.getInputStream();
    BufferedInputStream bis = new BufferedInputStream(input);
    byte[] cache = new byte[1024];
    int n = 0;
    ByteArrayOutputStream baos = new ByteArrayOutputStream();
    while (-1 != (n = bis.read(cache))) {
        baos.write(cache, 0, n);
        if (n >= 1 && cache[n - 1] == '}') {
            break;
        }
    }
    return baos.toByteArray();
}

public static String getRawRequestBody(HttpServletRequest request) throws IOException {
    byte[] bytes = getRawRequestBodyBytes(request);
    return new String(bytes, StandardCharsets.UTF_8);
}
}
修改后现在是这样
public class HttpUtils {

public static byte[] getRawRequestBodyBytes(HttpServletRequest request) throws IOException {
ServletInputStream input = request.getInputStream();
BufferedInputStream bis = new BufferedInputStream(input);
byte[] cache = new byte[1024];
int n = 0;
ByteArrayOutputStream baos = new ByteArrayOutputStream();
while (-1 != (n = bis.read(cache))) {
baos.write(cache, 0, n);
if (n >= 1 && cache[n - 1] == '}') {
break;
}
}
return baos.toByteArray();
}

public static String getRawRequestBody(HttpServletRequest request) throws IOException {
byte[] bytes = getRawRequestBodyBytes(request);
return new String(bytes, StandardCharsets.UTF_8);
}
}

我是修改成这样，从HttpServletRequest读取json就验签成功了，

另外如果json的 } 后面如果还支持有空格

可以

public class HttpUtils {

public static byte[] getRawRequestBodyBytes(HttpServletRequest request) throws IOException {
    ServletInputStream input = request.getInputStream();
    BufferedInputStream bis = new BufferedInputStream(input);
    byte[] cache = new byte[1024];
    int n = 0;
    ByteArrayOutputStream baos = new ByteArrayOutputStream();
    while (-1 != (n = bis.read(cache))) {
        baos.write(cache, 0, n);
        if (n >= 1 && cache[n - 1] == '}') {
            bis.mark(1); // 标记当前位置
            try {
                do {
                    n = bis.read(cache);
                    if (n == -1) {
                        break;
                    }
                } while (Character.isWhitespace(cache[0]));
                if (n != -1) {
                    continue;
                }
            } catch (IOException e) {
                bis.reset();
            }
            break;
        }
    }
    return baos.toByteArray();
}

public static String getRawRequestBody(HttpServletRequest request) throws IOException {
    byte[] bytes = getRawRequestBodyBytes(request);
    return new String(bytes, StandardCharsets.UTF_8);
}
}

**Comment by rocwang02** [comment]
> ```java
> HttpUtils
> ```

`    /**
     * 将通知参数转化为字符串
     * @param request
     * @return
     */
    public static String readData(HttpServletRequest request) {
        BufferedReader br = null;
        try {
            StringBuilder result = new StringBuilder();
            br = request.getReader();
            for (String line; (line = br.readLine()) != null; ) {
                if (result.length() > 0) {
                    result.append("\n");
                }
                result.append(line);
            }
            return result.toString();
        } catch (IOException e) {
            throw new RuntimeException(e);
        } finally {
            if (br != null) {
                try {
                    br.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }
    }`

**Comment by rocwang02** [comment]
> > ```java
> > HttpUtils.readData(request)
> > ```
> 
> @rocwang02 你好，可以提供下HttpUtils这个工具类吗

刚看到邮件，具体如下：
```java
    /**
     * 将通知参数转化为字符串
     * @param request
     * @return
     */
    public static String readData(HttpServletRequest request) {
        BufferedReader br = null;
        try {
            StringBuilder result = new StringBuilder();
            br = request.getReader();
            for (String line; (line = br.readLine()) != null; ) {
                if (result.length() > 0) {
                    result.append("\n");
                }
                result.append(line);
            }
            return result.toString();
        } catch (IOException e) {
            throw new RuntimeException(e);
        } finally {
            if (br != null) {
                try {
                    br.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }
    }
```

**Comment by rocwang02** [comment]
刚看到邮件，具体如下：
    /**      * 将通知参数转化为字符串      * @param request      * @return      */     public static String readData(HttpServletRequest request) {         BufferedReader br = null;         try {             StringBuilder result = new StringBuilder();             br = request.getReader();             for (String line; (line = br.readLine()) != null; ) {                 if (result.length() &gt; 0) {                     result.append("\n");                 }                 result.append(line);             }             return result.toString();         } catch (IOException e) {             throw new RuntimeException(e);         } finally {             if (br != null) {                 try {                     br.close();                 } catch (IOException e) {                     e.printStackTrace();                 }             }         }     }




王长鹏
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wechatpay-apiv3/wechatpay-java"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月1日(星期四) 晚上9:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wechatpay-apiv3/wechatpay-java] 支付结果通知验签失败(自动下载平台证书) (Issue #120)





  
修改后现在是这样 public class HttpUtils {
 public static byte[] getRawRequestBodyBytes(HttpServletRequest request) throws IOException {     ServletInputStream input = request.getInputStream();     BufferedInputStream bis = new BufferedInputStream(input);     byte[] cache = new byte[1024];     int n = 0;     ByteArrayOutputStream baos = new ByteArrayOutputStream();     while (-1 != (n = bis.read(cache))) {         baos.write(cache, 0, n);         if (n &gt;= 1 &amp;&amp; cache[n - 1] == '}') {             break;         }     }     return baos.toByteArray(); } public static String getRawRequestBody(HttpServletRequest request) throws IOException {     byte[] bytes = getRawRequestBodyBytes(request);     return new String(bytes, StandardCharsets.UTF_8); }  
}
 修改后现在是这样
 public class HttpUtils {
  
public static byte[] getRawRequestBodyBytes(HttpServletRequest request) throws IOException {
 ServletInputStream input = request.getInputStream();
 BufferedInputStream bis = new BufferedInputStream(input);
 byte[] cache = new byte[1024];
 int n = 0;
 ByteArrayOutputStream baos = new ByteArrayOutputStream();
 while (-1 != (n = bis.read(cache))) {
 baos.write(cache, 0, n);
 if (n &gt;= 1 &amp;&amp; cache[n - 1] == '}') {
 break;
 }
 }
 return baos.toByteArray();
 }
 
public static String getRawRequestBody(HttpServletRequest request) throws IOException {
 byte[] bytes = getRawRequestBodyBytes(request);
 return new String(bytes, StandardCharsets.UTF_8);
 }
 }
 
我是修改成这样，从HttpServletRequest读取json就验签成功了，
 
另外如果json的 } 后面如果还支持有空格
 
可以
 
public class HttpUtils {
 public static byte[] getRawRequestBodyBytes(HttpServletRequest request) throws IOException {     ServletInputStream input = request.getInputStream();     BufferedInputStream bis = new BufferedInputStream(input);     byte[] cache = new byte[1024];     int n = 0;     ByteArrayOutputStream baos = new ByteArrayOutputStream();     while (-1 != (n = bis.read(cache))) {         baos.write(cache, 0, n);         if (n &gt;= 1 &amp;&amp; cache[n - 1] == '}') {             bis.mark(1); // 标记当前位置             try {                 do {                     n = bis.read(cache);                     if (n == -1) {                         break;                     }                 } while (Character.isWhitespace(cache[0]));                 if (n != -1) {                     continue;                 }             } catch (IOException e) {                 bis.reset();             }             break;         }     }     return baos.toByteArray(); } public static String getRawRequestBody(HttpServletRequest request) throws IOException {     byte[] bytes = getRawRequestBodyBytes(request);     return new String(bytes, StandardCharsets.UTF_8); }  
}
