### ISSUE TITLE
支付的单商户平台、多商户平台的使用建议

### ISSUE THREAD

**Issue by taolive** [wechatpay-apiv3/wechatpay-java#122]
### 您的功能请求与问题有关吗？ 请描述您遇到的问题

目前越来越多的支付依赖于多个商户平台，因此在调用api时，可以支持不同商户平台进行切换

### 描述您想要的解决方案

伪代码：

1：注册config
// 注册第1个商户号
ConfigFactory factory = RSAAutoCertificateConfig.registry(merchantId,privateKeyFromPath,merchantSerialNumber,apiV3Key)

// 注册第2个商户号
factory = RSAAutoCertificateConfig.registry(merchantId2,privateKeyFromPath2,merchantSerialNumber2,apiV3Key2)

2：关联service
JsapiService api = JsapiService.bind(factory)

3 使用JsapiService
// 线程级切换，切换到指定的商户平台
factory.switch(merchantId)
PrepayResponse response = api.prepay(...)

factory.switch(merchantId2)
PrepayResponse response = api.prepay(...)

**Comment by xy-peng** [comment]
我先说下对你 issue 的理解：

1. 你的业务场景是有多个商户号，不同的请求可能要使用不同的商户号
2. 你希望：一个config支持多个商户号
3. 你希望：一个service支持多个商户号，需要时可以切换

我个人感觉，这个方案最大的问题是切换时线程不安全，切换和发送请求要原子，否则临界区间太长性能一定会影响的。其实你也写出来了。

目前的实现下，我的建议是

1. 每个商户号对应一个 `RSAAutoCertificateConfig`
2. 每个请求，构造商户号对应的临时 service，再发起请求。DefaultHttpClient 底层使用同一个 OkHttpClient 整体开销应该可控。

更好的可能方案是 Service 支持 pre-request config。

不过 RSAAutoCertificateConfig 已经很复杂，支持多个商户号，我持保留态度。使用方使用一个map维护应该就可以吧。

@taolive 你能否把遇到的问题，跟预期不符合的地方展开说一下？

**Comment by taolive** [comment]
> 我先说下对你 issue 的理解：
> 
> 1. 你的业务场景是有多个商户号，不同的请求可能要使用不同的商户号
> 2. 你希望：一个config支持多个商户号
> 3. 你希望：一个service支持多个商户号，需要时可以切换
> 
> 我个人感觉，这个方案最大的问题是切换时线程不安全，切换和发送请求要原子，否则临界区间太长性能一定会影响的。其实你也写出来了。
> 
> 目前的实现下，我的建议是
> 
> 1. 每个商户号对应一个 `RSAAutoCertificateConfig`
> 2. 每个请求，构造商户号对应的临时 service，再发起请求。DefaultHttpClient 底层使用同一个 OkHttpClient 整体开销应该可控。
> 
> 更好的可能方案是 Service 支持 pre-request config。
> 
> 不过 RSAAutoCertificateConfig 已经很复杂，支持多个商户号，我持保留态度。使用方使用一个map维护应该就可以吧。
> 
> @taolive 你能否把遇到的问题，跟预期不符合的地方展开说一下？


我们暂时把每个商户的config存储在一个大对象中（caffeine），每个请求获取不同的config并build JsapiService对象，然后进行接口操作，
因管理的商户号较多，目前10多个商户号（还在增长中），且商户号配置需在线编辑，所以涉及到删除、修改、新增 操作，此时可能需要对config中的线程池进行销毁，或者有无方法可以对config进行修改呢？

**Comment by xy-peng** [comment]
> 有无方法可以对config进行修改呢？

我希望 config 是 immutable 的，用的时候会更安全

> 此时可能需要对config中的线程池的指定任务进行cancel

这种情况，我们考虑一下

**Comment by taolive** [comment]
> > 有无方法可以对config进行修改呢？
> 
> 我希望 config 是 immutable 的，用的时候会更安全
> 
> > 此时可能需要对config中的线程池的指定任务进行cancel
> 
> 这种情况，我们考虑一下。原则上是应该提供完整生命周期管理，供上层应用使用。
> 
> 顺便问一下，你是否考虑下把商户号管理和签名的功能从业务接口调用服务中独立出来，这样整体开销和安全性会更好一些。



> 我希望 config 是 immutable 的，用的时候会更安全
re：这个也合理，不过最好能提供config生命周期管理，毕竟config有一个自带的证书刷新策略


> 顺便问一下，你是否考虑下把商户号管理和签名的功能从业务接口调用服务中独立出来，这样整体开销和安全性会更好一些
re：暂时没有这样，但是希望证书秘钥是否可以提供接口出来，外部可以维护呢，或者外部可以共享？比如微服务，可能会部署多个支付服务，且管理多个商户，这样会导致config出问题

**Comment by xy-peng** [comment]
> 暂时没有这样，但是希望证书秘钥是否可以提供接口出来，外部可以维护呢，或者外部可以共享？比如微服务，可能会部署多个支付服务，且管理多个商户，这样会导致config出问题

@taolive 对于这种场景，我还是建议基于 SDK 做一个独立的微服务，统一管理商户号并提供签名相关的服务。这种方式实现外部可维护。

你所说的“外部可以维护”“外部可以共享”的外部是指，不同的服务间吗
