### ISSUE TITLE
没有下单回调通知的解密对象

### ISSUE THREAD

**Issue by 1qq8** [wechatpay-apiv3/wechatpay-java#123]
### 您的功能请求与问题有关吗？ 请描述您遇到的问题

我在文档里只看到了支付结果通知和退款结果通知所使用的解密对象，但是没有下单回调通知的解密对象

### 描述您想要的解决方案

需要一个下单通知的解密对象

**Comment by taolive** [comment]
NotificationParser parser = new NotificationParser(config);
// 验签并解密报文
final HashMap parse = parser.parse(requestParam, HashMap.class);
