### ISSUE TITLE
服务商转账功能 partnerTransferBatch

### ISSUE THREAD

**Issue by 1194117884** [wechatpay-apiv3/wechatpay-java#125]
### 您的功能请求与问题有关吗？ 请描述您遇到的问题

版本：maven Center 中 0.2.5
问题：未发现服务商下的批量转账到微信零钱，能否增加相应模块。
PS：猜测模块是 partnerTransferBatch
![image](https://user-images.githubusercontent.com/12094568/215260978-5f98c938-81a9-49b6-b955-2703af1d4125.png)

**Comment by Memory-9527** [comment]
服务商模式的现在走的是工卡，你有服务商批量付款产品权限？
