### ISSUE TITLE
建议ShaUtil增加getSha1HexString(byte[] source) 的实现

### ISSUE THREAD

**Issue by guantou** [wechatpay-apiv3/wechatpay-java#126]
### 您的功能请求与问题有关吗？ 请描述您遇到的问题

ShaUtil仅提供了一个Sha1的public方法
```
ShaUtil.getSha1HexString(InputStream inputStream)
```

以及一个private方法:
```
private static String getShaHexString(InputStream inputStream, String algorithm) 
```

实际场景中：
账单下载后校验哈希值，此时已拿到账单文件内容字符串，由于ShaUtil缺少```getSha1HexString(byte[] source)``` ，以及```getShaHexString(InputStream inputStream, String algorithm) ``` 为private , 导致无法直接对字符串完成哈希计算，需要自行实现getSha1HexString方法。

### 描述您想要的解决方案

建议ShaUtil增加getSha1HexString(byte[] source) 的实现，同已有的```public static String getSha256HexString(InputStream inputStream)```一样

**Comment by xy-peng** [comment]
考虑到账单文件可能会很大，我们建议先把账单以临时文件写入文件系统，再以流的方式读入，验证摘要值。

如果你对 `getSha1HexString(byte[] source)` 有需要，我们欢迎协同提交 PR。
