### ISSUE TITLE
当前版本是否可以应用于线上环境

### ISSUE THREAD

**Issue by opcooc** [wechatpay-apiv3/wechatpay-java#128]

**Comment by xy-peng** [comment]
完全可以。

SDK 虽然是按照微信支付认为的最佳实践开发的，但开发者正确使用也很重要。应用于线上环境的话，你们还是应做完整的测试和验证。

**Comment by opcooc** [comment]
> 完全可以。
> 
> SDK虽然是按照微信支付认为的最佳实践开发的，但开发者正确使用也很重要。应用在线上环境的话，你们一定要做谦和诚恳的说。

好的感谢
