### ISSUE TITLE
Jsapi验证response时证书序列号不正确

### ISSUE THREAD

**Issue by zl15473145** [wechatpay-apiv3/wechatpay-java#132]
### 错误描述

Jsapi验证response时证书序列号不正确。
response headers中返回的Wechatpay-Serial 非商户的Serial 导致验证失败

### 重现bug的步骤

使用com/wechat/pay/java/service/payments/jsapi)/JsapiServiceExtensionExample.java
 public static String merchantId = "";
  public static String privateKeyPath = "";
  public static String merchantSerialNumber = "";
  public static String wechatPayCertificatePath = "";
  public static JsapiServiceExtension service;

  public static void main(String[] args) {
    // 初始化商户配置
    RSAConfig config =
        new RSAConfig.Builder()
            .merchantId(merchantId)
            // 使用 com.wechat.pay.java.core.util 中的函数从本地文件中加载商户私钥，商户私钥会用来生成请求的签名
            .privateKeyFromPath(privateKeyPath)
            .merchantSerialNumber(merchantSerialNumber)
            .wechatPayCertificatesFromPath(wechatPayCertificatePath)
            .build();
    // 初始化服务
    service =
        new JsapiServiceExtension.Builder()
            .config(config)
            .signType("RSA") // 不填默认为RSA
            .build();
    try {
      // ... 调用接口
      PrepayWithRequestPaymentResponse response = prepayWithRequestPayment();
      System.out.println(response);
    } catch (HttpException e) { // 发送HTTP请求失败
      // 调用e.getHttpRequest()获取请求打印日志或上报监控，更多方法见HttpException定义
    } catch (ServiceException e) { // 服务返回状态小于200或大于等于300，例如500
      // 调用e.getResponseBody()获取返回体打印日志或上报监控，更多方法见ServiceException定义
    } catch (MalformedMessageException e) { // 服务返回成功，返回体类型不合法，或者解析返回体失败
      // 调用e.getMessage()获取信息打印日志或上报监控，更多方法见MalformedMessageException定义
    }
  }
  /** 关闭订单 */
  public static void closeOrder() {

    CloseOrderRequest request = new CloseOrderRequest();
    // 调用request.setXxx(val)设置所需参数，具体参数可见Request定义
    // 调用接口
    service.closeOrder(request);
  }
  /** JSAPI支付下单，并返回JSAPI调起支付数据 */
  public static PrepayWithRequestPaymentResponse prepayWithRequestPayment() {
    PrepayRequest request = new PrepayRequest();
    // 调用request.setXxx(val)设置所需参数，具体参数可见Request定义
    // 调用接口
    return service.prepayWithRequestPayment(request);
  }
  /** 微信支付订单号查询订单 */
  public static Transaction queryOrderById() {

    QueryOrderByIdRequest request = new QueryOrderByIdRequest();
    // 调用request.setXxx(val)设置所需参数，具体参数可见Request定义
    // 调用接口
    return service.queryOrderById(request);
  }
  /** 商户订单号查询订单 */
  public static Transaction queryOrderByOutTradeNo() {

    QueryOrderByOutTradeNoRequest request = new QueryOrderByOutTradeNoRequest();
    // 调用request.setXxx(val)设置所需参数，具体参数可见Request定义
    // 调用接口
    return service.queryOrderByOutTradeNo(request);
  }
}

### 预期行为

无

### 导致错误的代码片段

```Java
public boolean verify(String serialNumber, String message, String signature) {
        X509Certificate certificate = this.certificateProvider.getCertificate(serialNumber);
        if (certificate == null) {
            logger.error("Verify the signature and get the WechatPay certificate corresponding to serialNumber[{}] is empty.", serialNumber);
            return false;
        } else {
            return this.verify(certificate, message, signature);
        }
    }
```

### 操作系统

windows

### Java 版本

8

### wechatpay-java 版本

0.0.25

**Comment by zl15473145** [comment]
1

**Comment by kmlkirito** [comment]
怎么没有说明就移除了这条bug
