### ISSUE TITLE
我在调用拉起支付时，在体验版苹果和安卓都可以拉起并支付，但是审核通过之后，苹果就支付失败了

### ISSUE THREAD

**Issue by xingwenkai** [wechatpay-apiv3/wechatpay-java#133]
### 错误描述

![image](https://user-images.githubusercontent.com/61527421/216888439-35dc63a5-0e6d-4a5f-896e-99751dbbd916.png)
我在调用拉起支付时，在体验版苹果和安卓都可以拉起并支付，但是审核通过之后，苹果就支付失败了，拉不起支付页面，这个是因为什么呀？

### 重现bug的步骤

我在调用拉起支付时，在体验版苹果和安卓都可以拉起并支付，但是审核通过之后，苹果就支付失败了，拉不起支付页面，这个是因为什么呀？

### 预期行为

希望都可以拉起支付

### 操作系统

ios

### Java 版本

8

### wechatpay-java 版本

0.2.4

**Comment by xy-peng** [comment]
出错原因还得看错误消息呀。
