### ISSUE TITLE
JsapiService和JsapiServiceExtension这两个类有什么业务场景上的区别吗

### ISSUE THREAD

**Issue by MonkeyCoder128** [wechatpay-apiv3/wechatpay-java#137]
### 错误描述

小程序支付的第一步也是调用JSAPI下单,这两个类上都有调用JSAPI下单的方法.只是返回类型不同.是使用业务场景上的区别吗?

![image](https://user-images.githubusercontent.com/42332199/218685216-08a39a91-bce4-4675-b845-59b29e545a2e.png)

![image](https://user-images.githubusercontent.com/42332199/218685387-ba307fce-fc54-4d8a-a4d0-db7e842142f4.png)

### 重现bug的步骤

RT

### 预期行为

希望能够将区别和使用场景添加到类注释上描述清楚

### 操作系统

windows11

### Java 版本

jdk1.8

### wechatpay-java 版本

v0.2.5

**Comment by xy-peng** [comment]
`JsapiService` 是根据 JSAPI 支付 API 自动生成调用代码。
`JsapiServiceExtension` 封装了 `JsapiService`，提供了下单并生成调起支付参数的接口，这样不用开发者自己组参数和计算签名了。对于开发者而言，更加方便。

建议使用 `JsapiServiceExtension`。我们完善下文档。最好的方式是在支付 API 文档中提供使用 SDK 的示例代码，我们也在推进。
