### ISSUE TITLE
Payer实体字段与官方文档不一致

### ISSUE THREAD

**Issue by gitot** [wechatpay-apiv3/wechatpay-java#144]
### 您的功能请求与问题有关吗？ 请描述您遇到的问题

[小程序下单时](https://pay.weixin.qq.com/wiki/doc/apiv3_partner/apis/chapter4_5_1.shtml)，请求参数需要传递支付用户信息 Payer。

sdk中的实体中的字段与文档中不一致。

![image](https://user-images.githubusercontent.com/45475681/225182641-1eab285b-a30e-4d28-865b-a3b73b4a3ee6.png)

![image](https://user-images.githubusercontent.com/45475681/225183040-0257c8c2-aaac-4f41-be59-b60918fb943c.png)

**Comment by xy-peng** [comment]
服务商的实现在 service/partnerpayments 下，Payer 定义在是

```java
/** TransactionPayer */
public class TransactionPayer {
  /** spOpenid */
  @SerializedName("sp_openid")
  private String spOpenid;
  /** subOpenid */
  @SerializedName("sub_openid")
  private String subOpenid;
}
```

**Comment by gitot** [comment]
好的，感谢
