### ISSUE TITLE
关于API v3调用问题。

### ISSUE THREAD

**Issue by haihuawang** [wechatpay-apiv3/wechatpay-java#148]
### 错误描述

看到文档：https://pay.weixin.qq.com/wiki/doc/apiv3/wechatpay/wechatpay-1.shtml 中描述：
![image](https://user-images.githubusercontent.com/32292200/226554184-76bccf43-10ab-4a7f-959f-f2680f5a3b6d.png)

不再要求携带HTTPS客户端证书（仅需携带证书序列号）

但是从文档中的实例代码还是需要传 证书Path。

privateKeyFromPath

### 重现bug的步骤

文档问题

### 预期行为

是否需要加一些注释说明？

### 导致错误的代码片段

```Java
Config config =
                new RSAAutoCertificateConfig.Builder()
                        .merchantId(merchantId)
                        .privateKeyFromPath(privateKeyPath)
                        .merchantSerialNumber(merchantSerialNumber)
                        .apiV3Key(apiV3key)
                        .build();
```

### 操作系统

MacOs

### Java 版本

Java 18

### wechatpay-java 版本

v0.2.7

**Comment by xy-peng** [comment]
介绍中讲的是不再使用 HTTPS 双向认证。但是 APIv3 仍然需要用商户 API 私钥签名，传私钥文件的路径。

我们把文档中心的文档写得更准确。

**Comment by chaspetter** [comment]
natvie 和jsapi同时使用一个apiv3的RSAAutoCertificateConfig，native正常使用， 但是jsapi调用会报错“支付验证签名失败”， 这个有可能是证书的问题吗？  前端是直接调用后端返回的签名参数

**Comment by xy-peng** [comment]
https://pay.weixin.qq.com/docs/merchant/development/interface-rules/introduction.html

新文档已经重写该部分内容
