### ISSUE TITLE
NotificationParser 不能使用RSAConfig构造么？

### ISSUE THREAD

**Issue by ZhangY18** [wechatpay-apiv3/wechatpay-java#149]
### 错误描述

发现NotificationParser 不能使用RSAConfig构造，是不是我在用到支付回调通知功能时，我必须要实现RSAAutoCertificateConfig？

### 重现bug的步骤

无

### 预期行为

得到回答

### 操作系统

windows

### Java 版本

java 8

### wechatpay-java 版本

0.2.7

**Comment by xy-peng** [comment]
1. 你可以使用 [RSANotificationConfig](https://github.com/wechatpay-apiv3/wechatpay-java/blob/main/core/src/main/java/com/wechat/pay/java/core/notification/RSANotificationConfig.java)，它使用的本地的微信支付平台证书。
2. `RSAConfig` 和 `RSANotificationConfig` 两者的参数集不一样，分开能让两个场景更简单。而 `RSAAutoCertificateConfig` 共用是因为两个场景的参数集是一样的，也希望共用一个自动下载证书。

**Comment by ZhangY18** [comment]
好的
