### ISSUE TITLE
有对账单申请的demo么

### ISSUE THREAD

**Issue by ttddss** [wechatpay-apiv3/wechatpay-java#151]
### 您的功能请求与问题有关吗？ 请描述您遇到的问题

![image](https://user-images.githubusercontent.com/29658865/228191700-386025cf-226b-4cf1-88d6-c6cf4ae513b0.png)

**Comment by xy-peng** [comment]
下载账单几行代码就可以，请参考 [下载账单](https://github.com/wechatpay-apiv3/wechatpay-java#%E4%B8%8B%E8%BD%BD%E8%B4%A6%E5%8D%95)

你需要demo是因为哪一部分不知道如何操作？

**Comment by ttddss** [comment]
申请交易账单请求

**Comment by xy-peng** [comment]
申请交易账单，先阶段没有提供具体的 SDK 方法，要自己拼请求 URL 通过 HttpClient [发送 HTTP 请求](https://github.com/wechatpay-apiv3/wechatpay-java#%E5%8F%91%E9%80%81-http-%E8%AF%B7%E6%B1%82)。

感谢你的提问。暂时没有具体的某个业务接口的 demo。未来，包含 SDK 示例代码的业务侧开发指南也许会慢慢补充上来。

发送 HTTP 请求的地方确实没有文档，我可以补充一个通用的示例。
