### ISSUE TITLE
V3单商户多个实例支持

### ISSUE THREAD

**Issue by C20171008S** [wechatpay-apiv3/wechatpay-java#152]
### 您的功能请求与问题有关吗？ 请描述您遇到的问题

  目前我们系统采取缓存RSAAutoCertificateConfig设置5分钟过期防止配置变化，而且我们的key采取的是商店id，两个商店可能配置同一个mchId这个时候会产生两个实例，就会出现问题。

### 描述您想要的解决方案

  下载证书不要按照mchId的粒度进行下载，要按照RSAAutoCertificateConfig实例为key进行下载,可以在每一个RSAAutoCertificateConfig产生一个uuid作为证书的key

**Comment by xy-peng** [comment]
问题的还是，`RSAAutoCertificateConfig` 限制了只允许每个商户号设置一遍，而不是每个商户号只下载一次。

暂时建议在你们的商店和商户号之间做一层适配器。如何优化 `RSAAutoCertificateConfig` 让其更适应各种商户系统侧的场景，我们再思考下。
