### ISSUE TITLE
关于服务商模式电商收付通相关功能

### ISSUE THREAD

**Issue by hailiangliu** [wechatpay-apiv3/wechatpay-java#157]
### 您的功能请求与问题有关吗？ 请描述您遇到的问题

请问目前版本中支持电商收付通相关的接口吗
微信支付官方服务商相关接口
电商收付通相关https://pay.weixin.qq.com/wiki/doc/apiv3_partner/apis/chapter7_1_1.shtml

fork了相关代码没有找到到进件相关的接口~

**Comment by xy-peng** [comment]
如果有需要的功能不支持，请反馈至微信支付的 [开发者社区](https://developers.weixin.qq.com/community/pay)。社区的渠道有专人收集开发者的功能需求。

issue 反馈缺陷或者 SDK 的基础能力吧。
