### ISSUE TITLE
沙箱，微信支付没有沙箱吗

### ISSUE THREAD

**Issue by ops-xu** [wechatpay-apiv3/wechatpay-java#161]
### 您的功能请求与问题有关吗？ 请描述您遇到的问题

沙箱，微信支付没有沙箱吗

### 描述您想要的解决方案

沙箱，微信支付没有沙箱吗

### 您还有其他的方案吗？

沙箱，微信支付没有沙箱吗

### 其他信息

沙箱，微信支付没有沙箱吗

**Comment by misaya98** [comment]
没有，支付宝有
