### ISSUE TITLE
急需分账相关接口

### ISSUE THREAD

**Issue by GerogeLeon** [wechatpay-apiv3/wechatpay-java#169]
### 您的功能请求与问题有关吗？ 请描述您遇到的问题

java SDK  wechatpay-java 0.2.7 【最新】中没有分账相关接口。而它的替代SDK  wechatpay-apache-httpclient又不是官方推荐，并且它的最新release版本0.4.9仍为测试版本，而且不知道它的哪个版本是稳定版本。  急需分账接口！！！

注：查了源码，没找到，用全文检索工具也没有检索到分账相关的特有请求字段，如out_order_no

若实际上存在，请在本issue中贴给我，非常感谢！

### 描述您想要的解决方案
请在 wechatpay-java 中补充分账相关接口

### 其他信息

我预期SDK能覆盖你们公开的[API字典](https://pay.weixin.qq.com/wiki/doc/apiv3/apis/index.shtml)，现突然发现少接口，所以加急！加急！
若还有缺接口，也请补全吧，因为不知道啥时候业务突然要用到。产品经理看API字典中支持业务，但SDK中却没有，很煎熬人

注：若实际上存在，请忽略

**Comment by GerogeLeon** [comment]
虽然这些接口不是很复杂，但是加进来意义很大，因为能开箱即用了，就像spring boot。请重视！

**Comment by xy-peng** [comment]
收到，我们来推进

**Comment by Qdafengzi** [comment]
在SDK内我没看到任何profit_sharing的字段 ,所以来看看是否有人说分账的事情，果然 它真没有在SDK里面。

**Comment by wweiaixingxing** [comment]
@GerogeLeon 私聊我，我根据微信提供的sdk 自己封装了分账接口

**Comment by Qfinn** [comment]
> @GerogeLeon 私聊我，我根据微信提供的sdk 自己封装了分账接口，跟支付的接口默认一样

谢谢，已经做完了

**Comment by gotolibing** [comment]
> > @GerogeLeon 私聊我，我根据微信提供的sdk 自己封装了分账接口，跟支付的接口默认一样
> 
> 谢谢，已经做完了

请问你们是用什么方式实现的微信分账支付？微信sdk中没有这个功能。
