### ISSUE TITLE
沙箱环境支持

### ISSUE THREAD

**Issue by wosiwq** [wechatpay-apiv3/wechatpay-java#176]
### 您的功能请求与问题有关吗？ 请描述您遇到的问题

在老版本的文档中，明确的在 [支付验收指引](https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=23_1&index=2) 下写出了沙箱的地址，但SDK并未提供对应的方法，文档中也未提及如何修改base Url来更换到沙箱环境，这极大的增加了开发难度

### 描述您想要的解决方案

1.SDK给出对应的沙箱对象与方法
2.给出一个配置，可以在配置中手动指定为沙箱环境

**Comment by wosiwq** [comment]
当我没说，沙箱环境需要完成商户号才能开发
温馨提示：目前仅有v2接口提供沙箱(仿真)环境，需要商户号（父子商户号）才可调用
2021年就进V3了 什么之后沙箱环境也推进一下呢？

**Comment by xy-peng** [comment]
我们有计划，再等等吧
