### ISSUE TITLE
如何获取到wechatPayCertificateSerialNumber

### ISSUE THREAD

**Issue by FitzFever** [wechatpay-apiv3/wechatpay-java#177]
### 您的功能请求与问题有关吗？ 请描述您遇到的问题

java的SDK在 v0.2.3 版本，加入了自动更新平台证书的配置类 RSAAutoCertificateConfig。但当我在进行回调验签和解密时需要用到wechatPayCertificateSerialNumber。这个参数该如何获得？

**Comment by xy-peng** [comment]
敏感信息加密用 `PrivacyEncryptor`。在请求的 HTTP 头中传入的平台证书的证书序列号，可以通过 `PrivacyEncryptor.getWechatpaySerial()` 获取。

这个问题，我补充到常见问题中去。

**Comment by chenxin1215** [comment]
问题是这个RSAPrivacyEncryptor类构造的时候需要微信支付平台证书的证书序列号呀 这个序列号又去哪里拿呢？

![image](https://github.com/wechatpay-apiv3/wechatpay-java/assets/48000975/61dd908c-6cfe-4918-b6fc-efdb81a4181c)

**Comment by xy-peng** [comment]
从配置直接拿一个

```java
PrivacyEncryptor encryptor = config.createEncryptor();
```
