### ISSUE TITLE
能出一版兼容微信云托管的支付接口服务sdk吗

### ISSUE THREAD

**Issue by yaqian012** [wechatpay-apiv3/wechatpay-java#188]
### 您的功能请求与问题有关吗？ 请描述您遇到的问题

RT.能出一版兼容微信云托管的支付接口服务sdk吗

### 描述您想要的解决方案

现有云托管支付相关接口代理的当前微信支付，能否出一版兼容云托管的sdk

**Comment by xy-peng** [comment]
使用云托管实现支付功能已经相当简便，不需要关心证书、签名等琐事。所以，SDK 暂时不会兼容云托管。

当然，云托管上也可以直接使用 SDK，不用云托管的支付功能。
