### ISSUE TITLE
自动更新平台证书

### ISSUE THREAD

**Issue by lianup** [wechatpay-apiv3/wechatpay-java#19]
### 您的功能请求与问题有关吗？ 请描述您遇到的问题

提供自动更新平台证书能力，使用者不用传入平台证书。

### 描述您想要的解决方案

**修改点**
1. 增加 autoUpdateCertificateProvider，实现 CertificateProvider。
2. 修改 RSAConfig 的 Builder，如果不传 wechatPayCertificate，RSAConfig中的构造器传入 autoUpdateCertificateProvider。

**实现细节**
1. 封装安全单例线程池 SafeSingleScheduleExecutor。
2. autoUpdateCertificateProvider 中使用单例线程池 SafeSingleScheduleExecutor ，用于定时下载更新证书。
4. 使用原生的 okhttp 请求来下载证书。

**Comment by EmmetZC** [comment]
`CertificateProvidor` 是一个抽象名词，如果`AutoUpdateCertificateProvider` 已经是一个具体的实现的话，还是应该用更具体的命名。比如另一个库中的`AutoUpdateCertificateManager`之类的。

**Comment by EmmetZC** [comment]
> 如果不传 wechatPayCertificate，RSAConfig中的构造器传入 autoUpdateCertificateProvider。

这个我没太理解， `autoUpdateCertificateProvider` 是一个预先初始化好的单例吗？

- 如果是的话，那如果用户需要设置代理应该如何做？
- 如果不是的话，这个默认传`autoUpdateCertificateProvider`的逻辑是如何实现的？

**Comment by lianup** [comment]
> CertificateProvidor 是一个抽象名词，如果AutoUpdateCertificateProvider 已经是一个具体的实现的话，还是应该用更具体的命名。比如另一个库中的AutoUpdateCertificateManager之类的。

这里的命名是按照语言习惯使用实现名称+接口名来命名，像 InMemoryCertificateProvider 也是，因为功能是一样的，所以我希望保持一致。

**Comment by lianup** [comment]
> 如果是的话，那如果用户需要设置代理应该如何做？
如果不是的话，这个默认传autoUpdateCertificateProvider的逻辑是如何实现的？

之前的设想是，根据用户传入的参数初始化一个实例。但没法设置代理。因此改为由用户传入，提供设置代理的方法。类似：
```java
AutoUpdateCertificateProvider provider = new AutoUpdateCertificateProvider.Builder().proxy(proxy).build();
Config config = new RSAConfig.Builder().provider(provider).xxx.build();
// 可以调用putMerchant来添加商户
provider.putMerchant(mchId, privateKey, apiv3Key);
```

**Comment by EmmetZC** [comment]
> 
> 之前的设想是，根据用户传入的参数初始化一个实例。但没法设置代理。因此改为由用户传入，提供设置代理的方法。类似：
> 
> ```java
> AutoUpdateCertificateProvider provider = new AutoUpdateCertificateProvider.Builder().proxy(proxy).build();
> Config config = new RSAConfig.Builder().provider(provider).xxx.build();
> // 可以调用putMerchant来添加商户
> provider.putMerchant(mchId, privateKey, apiv3Key);
> ```

那就是 `RSAConfig` 要么传一个 `wechatPayCertificate` 要么传一个 `certificateProvider` 对吧？

**Comment by lianup** [comment]
> 那就是 `RSAConfig` 要么传一个 `wechatPayCertificate` 要么传一个 `certificateProvider` 对吧？

是的。

**Comment by xy-peng** [comment]
@lianup 发一下用户侧看起来的代码示例？

**Comment by lianup** [comment]
> @lianup 发一下用户侧看起来的代码示例？
```java
    // 初始化商户配置
    RSAConfig config =
        new RSAConfig.Builder()
            .merchantId(merchantId)
            // 使用 com.wechat.pay.java.core.util
            // 中的函数从本地文件中加载商户私钥，商户私钥会用来生成请求的签名
            .privateKeyFromPath(privateKeyPath)
            .merchantSerialNumber(merchantSerialNumber)
            .certificateProvider(new AutoUpdateCertificateProvider.Builder().merchantId(merchantId)
                .merchantSerfialNumber(merchantSerialNumber)
                .build())
            .build();

    // 初始化服务
    service = new JsapiService.Builder().config(config).build();
    // ... 调用接口
```

**Comment by qingdengyideng** [comment]
大神，这个自动更新平台证书的啥时候正式发布啊？0.2.1版本中没有找到certificateProvider诶

**Comment by royalzzz** [comment]
请问，这个enhancement会在什么版本发布？目前没有很优雅的方式实现自动更新平台证书，很急。
