### ISSUE TITLE
请问SDK中关于请求的域名可否支持自定义配置

### ISSUE THREAD

**Issue by heihuhu12010** [wechatpay-apiv3/wechatpay-java#193]
### 您的功能请求与问题有关吗？ 请描述您遇到的问题

RSAAutoCertificateProvider自动更新平台证书提供器中
private static final String REQUEST_URL =
      "https://api.mch.weixin.qq.com/v3/certificates?algorithm_type=RSA"; // 下载证书url
此值无法修改，但是系统目前只支持自定义的代理请求，无法完成该操作

### 描述您想要的解决方案

希望可以支持此属性进行自定义配置

**Comment by xy-peng** [comment]
已经支持了，请看 #16

我们常见问题里补充说明下。

**Comment by heihuhu12010** [comment]
是我们系统域名都是通过代理的方式配置，否则无法调用外部接口，比如https://api.mch.weixin.qq.com需要替换成 http://192.168.x.x

**Comment by xy-peng** [comment]
代理是否可以使用 `proxy()` 配置代理？参考 wiki 的说明 [代理配置（v0.2.6起开始支持）](https://github.com/wechatpay-apiv3/wechatpay-java/wiki/SDK-%E9%85%8D%E7%BD%AE%E8%AF%A6%E8%A7%A3#%E4%BB%A3%E7%90%86%E9%85%8D%E7%BD%AEv026%E8%B5%B7%E5%BC%80%E5%A7%8B%E6%94%AF%E6%8C%81)
