### ISSUE TITLE
热更新config配置

### ISSUE THREAD

**Issue by ytlrr0** [wechatpay-apiv3/wechatpay-java#202]
### 您的功能请求与问题有关吗？ 请描述您遇到的问题

<img width="1306" alt="image" src="https://github.com/wechatpay-apiv3/wechatpay-java/assets/6671717/675eb419-0b14-499f-8e61-799523f635ae">
如上所示代码块，导致了商户config对象，无法热更新，这块对商户管理服务来说不太友好。我们现在是自己继承了代码重写很多代码实现的。希望能提供这样的能力。

### 描述您想要的解决方案

config对象自己实现，AbstractAutoCertificateProvider也要自己实现一个
RSACertificateConfig是我们config的实现
<img width="845" alt="image" src="https://github.com/wechatpay-apiv3/wechatpay-java/assets/6671717/bf6ca0df-c065-48bb-ab78-7aad16f78c2d">
核心是build使用我们重写provider
<img width="1029" alt="image" src="https://github.com/wechatpay-apiv3/wechatpay-java/assets/6671717/f0341cbe-3770-4d77-a156-cd6d0f16e139">

config创建时，判断当前config在内存中是否存在，如果不存在再创建。
<img width="1044" alt="image" src="https://github.com/wechatpay-apiv3/wechatpay-java/assets/6671717/f582731a-5a8f-4203-adc7-268f0a521649">
RSACertificateProvider对象是我们继承AbstractAutoCertificateProvider并增加一个map来存储商户和config的关系。
<img width="1041" alt="image" src="https://github.com/wechatpay-apiv3/wechatpay-java/assets/6671717/b9e468a2-84bf-4a7e-be9f-8cec2e3fbdcc">
getRSACertificateConfig 方法实现如下
<img width="924" alt="image" src="https://github.com/wechatpay-apiv3/wechatpay-java/assets/6671717/acd43a41-12d6-4db6-a97e-25350be559f1">

### 其他信息

sdk版本：wechatpay-java:0.2.5

**Comment by xy-peng** [comment]
#194 是使用单一线程，串行更新添加过的商户的微信支付平台证书，并且提供对应的商户配置更新机制。

有一个待修改点：在更新商户配置时，是否要实时下载平台证书，并当配置错误导致下载失败时抛出异常。这样能减小更新时出现使用方难以感知的失败。不过，写代码时得要处理对应的异常。

欢迎 @ytlrr0 提出自己的建议和意见。

**Comment by ytlrr0** [comment]
能否提供对外删除config的api。因为配置错误在支付api调用过程中可以感知，也就是在支付出现异常时，可以清理错误配置。
我之前是重写这部分map提供可根据商户id删除配置的方法。

**Comment by ytlrr0** [comment]
<img width="735" alt="image" src="https://github.com/wechatpay-apiv3/wechatpay-java/assets/6671717/dfbce28b-09a5-4e09-90a7-2a7abc906a45">
调用支付预下单，被扫等api时 出现异常，清理配置。
<img width="925" alt="image" src="https://github.com/wechatpay-apiv3/wechatpay-java/assets/6671717/d80b42ed-d4b8-44b6-86aa-d7547d324c13">

**Comment by xy-peng** [comment]
> 能否提供对外删除config的api。因为配置错误在支付api调用过程中可以感知，也就是在支付出现异常时，可以清理错误配置。 我之前是重写这部分map提供可根据商户id删除配置的方法。

有 `AutoCertificateService.unregister()` 方法

**Comment by xy-peng** [comment]
调用支付预下单，被扫等api时 出现异常，清理配置。

== 为什么这么设计呢？

**Comment by ytlrr0** [comment]
这样设计的原因是我们商户配置管理功能目前不能提供证书配置正确与否的校验，因为财务等的要求以及和其他系统之间的数据平衡，导致配置的错误率很高。所以我们的支付过程中一般存在问题绝大多数情况下都是配置错误，所以我们就一刀切的做了这样一种选择，只要存在支付错误就清理内存config对象，这样也有问题就是异步定时任务没有被清理。如果官方提供校验能力api那是最好的了。

**Comment by xy-peng** [comment]
不需要单独的检查API，下载微信支付平台证书验证配置是否正确即可。

计划在构造 Config 时，如果不能下载平台证书，就尽早地报错。这样也符合“快速失败”的API设计原则。

**Comment by ytlrr0** [comment]
> 不需要单独的检查API，下载微信支付平台证书验证配置是否正确即可。
> 
> 计划在构造 Config 时，如果不能下载平台证书，就尽早地报错。这样也符合“快速失败”的API设计原则。

妙啊，这样确实更合理，期待新版本
