### ISSUE TITLE
支付回调，wechatPayCertificateSerialNumber 跟 serialNumber 请问是同一个东西吗

### ISSUE THREAD

**Issue by listener-He** [wechatpay-apiv3/wechatpay-java#205]
### 错误描述

无法确定wechatPayCertificateSerialNumber 是什么值 没有出处

### 重现bug的步骤

支付回调

### 预期行为

变量名词解释

### 操作系统

macOs

### Java 版本

Java 11

### wechatpay-java 版本

0.2.9

### 其他信息

wechatPayCertificateSerialNumber

**Comment by xy-peng** [comment]
`wechatPayCertificateSerialNumber` 对应 [微信支付平台证书](https://pay.weixin.qq.com/docs/merchant/development/interface-rules/privatekey-and-certificate.html#%E5%BE%AE%E4%BF%A1%E6%94%AF%E4%BB%98%E5%B9%B3%E5%8F%B0%E8%AF%81%E4%B9%A6)

**Comment by xy-peng** [comment]
我在 README 中补充说明下。最近也在计划为回调写一份更详细的开发指引。

**Comment by xiangdyzz** [comment]
> 我在 README 中补充说明下。最近也在计划为回调写一份更详细的开发指引。

很急，现在这份文档看的我头晕
