### ISSUE TITLE
最新版本0.2.11在Maven Central 找不见

### ISSUE THREAD

**Issue by wsxgun** [wechatpay-apiv3/wechatpay-java#217]
### 错误描述

使用最新的maven依赖，引入0.2.11的jar包，找不见，在Maven Central 中也没有

### 重现bug的步骤

 
![image](https://github.com/wechatpay-apiv3/wechatpay-java/assets/8391609/92c88616-e6cc-40e9-8f2c-1f25ca293764)

### 预期行为

希望能引用到

### 操作系统

v

### Java 版本

v

### wechatpay-java 版本

v

**Comment by xy-peng** [comment]
已经 release 了
