### ISSUE TITLE
商家转账到零钱无法使用静态路径

### ISSUE THREAD

**Issue by ouzechang** [wechatpay-apiv3/wechatpay-java#224]
### 错误描述

/v3/transfer/batches这个接口中需要用到privateKeyPath无法使用项目中的静态路径,只能按照绝对路径去访问

### 重现bug的步骤

使用HttpPayUtil.postTransBatRequest方法时最后一个参数需要填写绝对路径

### 预期行为

我希望使用流去操作,通过resourceLoader.getResource(path).getInputStream()去传入进去,而非一个绝对路径

### 导致错误的代码片段

```Java
String s = HttpPayUtil.postTransBatRequest(
                "https://api.mch.weixin.qq.com/v3/transfer/batches",
                jsonString,
                "",
                "","绝对路径下的/apiclient_key_feixia.pem"
                );
```

### 操作系统

centos7

### Java 版本

java8

### wechatpay-java 版本

0.0.1

### 其他信息

希望使用流传入inputstream然后操作去读取key.pem,传入绝对路径这个操作一方面不安全,一方面调试不方便

**Comment by xy-peng** [comment]
你这不是用的 wechatpay-java 吧？
