### ISSUE TITLE
这些没有返回值，也没有异常抛出的，如何进行处理

### ISSUE THREAD

**Issue by liulizhen9912** [wechatpay-apiv3/wechatpay-java#228]
### 您的功能请求与问题有关吗？ 请描述您遇到的问题

GoldPlanServiceExample.openAdvertisingShow

### 描述您想要的解决方案

是否可以接收对应的异常，http状态码 如何接收

**Comment by liulizhen9912** [comment]
https://pay.weixin.qq.com/wiki/doc/apiv3_partner/apis/chapter8_5_4.shtml 这些状态码如何能获取

**Comment by xy-peng** [comment]
请参考 [错误处理](https://github.com/wechatpay-apiv3/wechatpay-java#%E9%94%99%E8%AF%AF%E5%A4%84%E7%90%86)。

状态码见 `httpStatusCode`，错误码和错误信息见 `errorCode` 和 `errorMessage`。 

> [ServiceException](https://github.com/wechatpay-apiv3/wechatpay-java/blob/main/core/src/main/java/com/wechat/pay/java/core/exception/ServiceException.java)：调用微信支付服务，发送 HTTP 请求成功，HTTP 状态码小于200或大于等于300。
状态码为5xx：主动重试。
状态码为其他：获取错误中的 errorCode 、errorMessage，上报监控和日志打印。
