### ISSUE TITLE
getTradeBill返回"请求的账单文件不存在"

### ISSUE THREAD

**Issue by gzsjw** [wechatpay-apiv3/wechatpay-java#238]
### 错误描述

使用示例BillDownloadServiceExample下载账单，验签通过了，但接口返回{"code":"NO_STATEMENT_EXIST","message":"请求的账单文件不存在"}，
一般是什么情况？

### 重现bug的步骤

1、POM
        <dependency>
            <groupId>com.github.wechatpay-apiv3</groupId>
            <artifactId>wechatpay-java</artifactId>
            <version>0.2.11</version>
        </dependency>

2、初始化
    // 初始化商户配置
    Config config =
        new RSAAutoCertificateConfig.Builder()
            .merchantId(merchantId)
            // 使用 com.wechat.pay.java.core.util 中的函数从本地文件中加载商户私钥，商户私钥会用来生成请求的签名
            .privateKeyFromPath(privateKeyPath)
            .merchantSerialNumber(merchantSerialNumber)
            .apiV3Key(apiV3Key)
            .build();

    // 初始化服务
    service = new BillDownloadService.Builder().config(config).build();
    // ... 调用接口
    QueryBillEntity queryBillEntity = getTradeBill();

3、getTradeBill
  public static QueryBillEntity getTradeBill() {

    GetTradeBillRequest request = new GetTradeBillRequest();
    request.setBillDate("2023-09-08");
    request.setBillType(BillType.ALL);
    return service.getTradeBill(request);

### 预期行为

返回账单下载地址

### 操作系统

windows 10

### Java 版本

jdk 1.8

### wechatpay-java 版本

0.2.11

**Comment by xy-peng** [comment]
业务问题，请去开发者社区提问
