### ISSUE TITLE
机构模式下使用该SDK的疑问

### ISSUE THREAD

**Issue by simlegate** [wechatpay-apiv3/wechatpay-java#241]
### 错误描述

机构模式下小程序支付异步通知的API中`微信支付订单号`这个字段名字是`id`。

https://pay.weixin.qq.com/wiki/doc/api_external/ch/apis/chapter3_3_11.shtml

<img width="1211" alt="image" src="https://github.com/wechatpay-apiv3/wechatpay-java/assets/2359726/b4a753d3-6bbb-4aff-a676-82881aa25f7d">

但是我看普通商户模式下这个字段又叫做`transaction_id`。
https://pay.weixin.qq.com/docs/partner/apis/partner-mini-program-payment/payment-notice.html
<img width="612" alt="image" src="https://github.com/wechatpay-apiv3/wechatpay-java/assets/2359726/8aadba36-bfe1-40c7-8e1e-6b55b37fe3d0">

SDK中model的字段也是`transaction_id`。
https://github.com/wechatpay-apiv3/wechatpay-java/blob/main/service/src/main/java/com/wechat/pay/java/service/partnerpayments/jsapi/model/Transaction.java

是这个SDK不支持机构模式的开发么？

### 重现bug的步骤

如错误描述

### 预期行为

希望SDK中支持机构模式的字段

### 操作系统

macOS

### Java 版本

Java 17

### wechatpay-java 版本

v0.2.12

**Comment by xy-peng** [comment]
机构模式，是指作为服务商（现在叫做合作伙伴）接入吗？

是的话，请看在合伙伙伴平台查看 [小程序支付通知](https://pay.weixin.qq.com/docs/partner/apis/partner-mini-program-payment/payment-notice.html) 的文档。

**Comment by simlegate** [comment]
https://pay.weixin.qq.com/wiki/doc/api_external/ch/apis/chapter3_5_11.shtml
<img width="970" alt="image" src="https://github.com/wechatpay-apiv3/wechatpay-java/assets/2359726/aa6d4201-a3d2-442e-b027-d0cd95f976c3">
应该是微信支付里面的服务提供商（service provider)


文档里面显示微信支付订单号是`id`。
<img width="1569" alt="image" src="https://github.com/wechatpay-apiv3/wechatpay-java/assets/2359726/2ba6194f-3107-4318-beb3-a80ede7b803f">

**Comment by xy-peng** [comment]
你贴的是境外支付的API，目前 SDK 还不支持。
