### ISSUE TITLE
SYSTEM_ERROR 系统繁忙，请稍后重试

### ISSUE THREAD

**Issue by jqsl2012** [wechatpay-apiv3/wechatpay-java#245]
### 错误描述

com.wechat.pay.java.core.exception.ServiceException: Wrong HttpStatusCode[500]
httpResponseBody[{"code":"SYSTEM_ERROR","message":"系统繁忙，请稍后重试"}] 

### 重现bug的步骤

按照 https://github.com/wechatpay-apiv3/wechatpay-java/blob/main/service/src/example/java/com/wechat/pay/java/service/QuickStart.java  这个来，报错了

### 预期行为

获取支付二维码

### 操作系统

centos

### Java 版本

jdk8

### wechatpay-java 版本

0.2.12

**Comment by xy-peng** [comment]
请检查参数是否填对了，或者找[在线的技术支持](https://support.pay.weixin.qq.com/online-service?from=wechatpay)解决吧
