### ISSUE TITLE
为什么和官方文档不一样??? https://pay.weixin.qq.com/wiki/doc/apiv3/open/pay/chapter2_8_2.shtml

### ISSUE THREAD

**Issue by Nisus-Liu** [wechatpay-apiv3/wechatpay-java#246]
### 错误描述

官方文档里的类, 都找不到了.
是文档落后了, 还是文档超前了??

### 重现bug的步骤

xxx

### 预期行为

xxx

### 操作系统

windows

### Java 版本

17

### wechatpay-java 版本

0.2.12

**Comment by xy-peng** [comment]
当前的官网的 SDK 文档是 [SDK&开发工具](https://pay.weixin.qq.com/docs/merchant/sdk-tools/sdk-tool.html)
