### ISSUE TITLE
网站接了微信登录和支付接口，请问手机端打开网站如何进行微信扫码登录和支付呢？

### ISSUE THREAD

**Issue by jqsl2012** [wechatpay-apiv3/wechatpay-java#247]
### 错误描述

RT

### 重现bug的步骤

1

### 预期行为

1

### 导致错误的代码片段

```Java
1
```

### 操作系统

1

### Java 版本

1

### wechatpay-java 版本

1

### 其他信息

1

**Comment by xy-peng** [comment]
非 SDK 的问题，可以去[开发者社区](https://developers.weixin.qq.com/community/pay)提问
