### ISSUE TITLE
如何接入服务商平台？

### ISSUE THREAD

**Issue by bytefox1024** [wechatpay-apiv3/wechatpay-java#249]
### 您的功能请求与问题有关吗？ 请描述您遇到的问题

我公司是做服务商平台，我想知道此 sdk 是否合适。因为看起来更像是普通商户的 sdk。如果可以，是否有响应的例子？

**Comment by xy-peng** [comment]
[文档](https://github.com/wechatpay-apiv3/wechatpay-java/blob/main/service/README.md)中写了支持哪些服务商的接口
