### ISSUE TITLE
企业付款到零钱没有吗？

### ISSUE THREAD

**Issue by yang2yang** [wechatpay-apiv3/wechatpay-java#26]

**Comment by Eric-Lee-Handyman** [comment]
这里具体是指哪个API，麻烦给下对应的文档链接，感谢~

**Comment by simll** [comment]
文档连接：https://pay.weixin.qq.com/wiki/doc/apiv3/apis/chapter4_3_1.shtml

之前是叫“企业转账到零钱”，现在改成了”商家转账到零钱“

**Comment by xl277541808** [comment]
我们也要做这个 功能 企业转账到零钱。给活动前几名的客户发钱

**Comment by xy-peng** [comment]
#61
