### ISSUE TITLE
JsapiServiceExtension能添加static修饰成全局变量吗？是否线程安全？

### ISSUE THREAD

**Issue by Akashic-A** [wechatpay-apiv3/wechatpay-java#263]
### 您的功能请求与问题有关吗？ 请描述您遇到的问题

JsapiServiceExtension service = new JsapiServiceExtension.Builder().config(config).signType("RSA").build();能添加static修饰成全局变量吗？会不会在多线程环境中不安全？

**Comment by Akashic-A** [comment]
顺便还想请教下NotificationParser是否也能设为static且多线程使用安全

**Comment by xy-peng** [comment]
理论上不会，是多线程安全的
