### ISSUE TITLE
CertificateServiceExample跑不通

### ISSUE THREAD

**Issue by aioos** [wechatpay-apiv3/wechatpay-java#27]
###  获取平台证书列表接口不需要验签

没有跳过验签的配置

### 重现bug的步骤

- `com.wechat.pay.java.core.RSAConfig` 要求配置公钥
- `com.wechat.pay.java.core.http.AbstractHttpClient` 默认验签

### 预期行为

期望支持跳过验签

### 操作系统

macOS

### Java 版本

Java 18

### wechatpay-java 版本

main 303a8adc

**Comment by lianup** [comment]
你好，第一次获取平台证书是无需验签的，可以通过[微信支付 APIv3 平台证书下载工具](https://github.com/wechatpay-apiv3/CertificateDownloader)得到，后续通过接口[获取平台证书列表](https://pay.weixin.qq.com/wiki/doc/apiv3/apis/wechatpay5_1.shtml)来获得平台证书，是需要验签的。

SDK里面的证书服务，是调用 `获取平台证书列表` 接口获得的，因此是需要验签的。

**Comment by aioos** [comment]
好的
