### ISSUE TITLE
Illegal base64 character 2d 报错

### ISSUE THREAD

**Issue by weir2010** [wechatpay-apiv3/wechatpay-java#277]
### 错误描述

Config config =
                new RSAAutoCertificateConfig.Builder()
                        .merchantId(sysConfig.weiXinPay().mchId())
                        .privateKeyFromPath("/Users/weir/git/weir-quarkus-shop/quarkus-server/src/main/resources/wxpay.pem")
                        .merchantSerialNumber(sysConfig.weiXinPay().privateKeyNo())
                        .apiV3Key(sysConfig.weiXinPay().apiV3Key())
                        .build();

{
    "message": "Illegal base64 character 2d"
}

### 重现bug的步骤

报错  {
    "message": "Illegal base64 character 2d"
}

### 预期行为

报错  {
    "message": "Illegal base64 character 2d"
}

### 操作系统

mac

### Java 版本

jdk21

### wechatpay-java 版本

0.2.12

**Comment by weir2010** [comment]
私钥的问题  解决了

**Comment by hello-jin** [comment]
请问是如何解决的，我也遇到同样的问题

**Comment by Jay2293** [comment]
> 请问如何解决，我也遇到同样的问题
你敢信，他居然要我取把密钥文件里面的 ----BEGIN XXXXX----- 这种删了才能用

**Comment by hello-jin** [comment]
试试这种方式
`/**
 * 更精细控制（如排除某些路径），可手动注册过滤器：
 */
@Configuration
public class CustomEncodingConfig {
 
    @Bean
    public FilterRegistrationBean<CharacterEncodingFilter> encodingFilter() {
        CharacterEncodingFilter filter = new CharacterEncodingFilter();
        filter.setEncoding("UTF-8");
        filter.setForceEncoding(true);

        FilterRegistrationBean<CharacterEncodingFilter> registration = new FilterRegistrationBean<>();
        registration.setFilter(filter);
        registration.addUrlPatterns("/xx/xxx/*"); // 仅作用于支付回调接口 回调接口的地址
        registration.setOrder(Ordered.HIGHEST_PRECEDENCE); // 最高优先级
        return registration;
    }
}`
