### ISSUE TITLE
jsapi service提供新的prepay函数，支持生成getBrandWCPayRequest参数

### ISSUE THREAD

**Issue by aioos** [wechatpay-apiv3/wechatpay-java#30]
### 您的功能请求与问题有关吗？ 请描述您遇到的问题

既然getBrandWCPayRequest的参数需要商户私钥签名，为什么不直接返回签名后的参数。

仅仅是为了与前端隔离吗？

### 描述您想要的解决方案

jsapi service提供新的prepay函数，支持生成getBrandWCPayRequest参数。

**Comment by xy-peng** [comment]
有此计划。Go SDK 就提供了 [PrepayWithRequestPayment()](https://github.com/wechatpay-apiv3/wechatpay-go/blob/7628bde2c8d1ade0c5b42529b61f00b5fcc152fc/services/payments/jsapi/api_jsapi_request_payment.go#L34)。

欢迎 PR。

**Comment by RonnieLincoln** [comment]
周末有空会尝试下。

看上去go sdk给client增加了singer。
```go
// Client 微信支付API v3 基础 Client
type Client struct {
	httpClient *http.Client
	credential auth.Credential
	validator  auth.Validator
	signer     auth.Signer
	cipher     cipher.Cipher
}
```

可以考虑给Credential添加getSign方法，再由HttpClient封装。

**Comment by aioos** [comment]
周末有空会尝试下。

看上去go sdk给client增加了singer。
```go
// Client 微信支付API v3 基础 Client
type Client struct {
	httpClient *http.Client
	credential auth.Credential
	validator  auth.Validator
	signer     auth.Signer
	cipher     cipher.Cipher
}
```

Java这里，可以考虑给Credential添加getSign方法，再由HttpClient封装。

**Comment by xy-peng** [comment]
> 周末有空会尝试下。

欢迎👏

> Java这里，可以考虑给Credential添加getSign方法，再由HttpClient封装。

我同意前半句，增加 `Credential.getSign()`。

不过，我倾向于从 `Config` 获得 `Signer`，而不是从 HttpClient 中获得。提供拉起前端小程序或者支付的签名计算，不是 HttpClient 的职责，绕一圈并不直观。

另外，`XXXService` 是根据契约自动生成的，不建议改动，需要单独定义一个类。举个例子，可能是

```java

public class JsapiServiceExtend {
  private JsapiService service;
  
  public JsapiServiceExtend(JsapiService, Signer);
}
```

以上是个人观点，欢迎讨论。

**Comment by huihui-hb** [comment]
> 有此计划。Go SDK 就提供了 [PrepayWithRequestPayment()](https://github.com/wechatpay-apiv3/wechatpay-go/blob/7628bde2c8d1ade0c5b42529b61f00b5fcc152fc/services/payments/jsapi/api_jsapi_request_payment.go#L34)。
> 
> 欢迎 PR。

:-1: 我本来想上V3，我看到这句我惊了，从新增的调用平台证书开始，我就非常怀疑微信支付api团队的技术能力。
有一说一微信支付的开发体验，比支付宝不是差了一点点。
