### ISSUE TITLE
RSAAutoCertificateConfig初始化报错

### ISSUE THREAD

**Issue by FutureHai** [wechatpay-apiv3/wechatpay-java#302]
### 错误描述

报错：{"code":"SYSTEM_ERROR","message":"系统繁忙，请稍后重试"}

### 重现bug的步骤

证书密钥都是正确的，使用“微信支付 APIv3 的调试工具”测试native下单可以正常返回二维码链接

### 预期行为

不出现异常

### 导致错误的代码片段

```Java
Config config =
                new RSAAutoCertificateConfig.Builder()
                        .merchantId(merchantId)
                        .privateKeyFromPath(privateKeyPath)
                        .merchantSerialNumber(merchantSerialNumber)
                        .apiV3Key(apiV3Key)
                        .build();
```

### 操作系统

macOS

### Java 版本

java21

### wechatpay-java 版本

0.2.14

### 其他信息

message:Wrong HttpStatusCode[500]
httpResponseBody[{"code":"SYSTEM_ERROR","message":"系统繁忙，请稍后重试"}] HttpRequest[{"http_method":"GET","url":"https://api.mch.weixin.qq.com/v3/certificates?algorithm_type=RSA","uri":"https://api.mch.weixin.qq.com/v3/certificates?algorithm_type=RSA","headers":{"headers":{"Authorization":"WECHATPAY2-SHA256-RSA2048 mchid="1696133332",nonce_str="12Ddbb6gvtQrgaaEyMoAk1iSMJ73NhUa",timestamp="1730106898",serial_no="7363A7390A020DC1714C23F4511483FF5F49B6C4",signature="mdfPiksn0pgDjuckUDRGpFcjEf+GnwWPlbjWRxoK8LhkD8x7gnLozX/8D3OyM4YOqISY6KoWWprzfZvelIN+3HfPc7JSBK7NvflJtB/LT35HJu+ih2VeLzOcRNyKxsZzQohjUKdOCrg6AylMDFaM7yo0G5gp0uuv1Un8KYwk2yGT72bl8g0tpWHzzkqK0dHTISklnedyYSzCiMFuykXetsrPrlta4zPILKQ601Dtdl8GgQaF884YwWxc6LG5YQab1qcommDKG4GWJLzGPNU+oefoDj53MPZicA+kSpxBhRTnWPN6DIOZwEcVnlAaMGC151qKK4bUK2+RZ67Ifq0coQ=="","Accept":" /","User-Agent":"WechatPay-Java/0.2.14 (Mac OS X/14.3) Java/21.0.2 Credential/WechatPay2Credential Validator/ okhttp3/null","Content-Type":"application/json"}}}]

**Comment by FutureHai** [comment]
message:Wrong HttpStatusCode[500]
httResponseBody[{"code":"SYSTEM_ERROR","message":"系统繁忙，请稍后重试"}]	HttpRequest[{"http_method":"GET","url":"https://api.mch.weixin.qq.com/v3/certificates?algorithm_type=RSA","uri":"https://api.mch.weixin.qq.com/v3/certificates?algorithm_type=RSA","headers":{"headers":{"Authorization":"WECHATPAY2-SHA256-RSA2048 mchid=\"1696133332\",nonce_str=\"ja158MOojgDppGciiqzlFxt306jRKLQJ\",timestamp=\"1730103718\",serial_no=\"7363A7390A020DC1714C23F4511483FF5F49B6C4\",signature=\"dwcu6VmmXIcRqir6HBS/cooQM0/3wCv7XRwHHfXngxDEOMGBkQ8DaDsbdGpevohGdD7PFVhrXwiYRy0xkYqrscWZrMf0/zVZIAhIgkFyXfbs1+KzK2qsmbcz8jEwktYu7PJKNbn/9Re+7uKllXc9Uc9pyW5WE4jOk1bKxZCubyihJ6j/W+hNnNoWrvm9j+qq6NVakhaFB9VdJnd7otzr2BDAUdeUUg+yUpk1+4dQPew/SMQXkW7BsUj9jO1GgYvlPxoOj832mVXN8iWcQdFbyVnqRJ5009Pf5utjgn8GoCaXQ77ttjKAf2Ib9ACpVsCs3PpAPOeIi+e9W9zRE2EmEw==\"","Accept":" */*","User-Agent":"WechatPay-Java/0.2.6 (Mac OS X/14.3) Java/21.0.2 Credential/WechatPay2Credential Validator/ okhttp3/null","Content-Type":"application/json"}}}]

**Comment by FutureHai** [comment]
message:Wrong HttpStatusCode[500]
httpResponseBody[{"code":"SYSTEM_ERROR","message":"系统繁忙，请稍后重试"}]	HttpRequest[{"http_method":"GET","url":"https://api.mch.weixin.qq.com/v3/certificates?algorithm_type=RSA","uri":"https://api.mch.weixin.qq.com/v3/certificates?algorithm_type=RSA","headers":{"headers":{"Authorization":"WECHATPAY2-SHA256-RSA2048 mchid=\"1696133332\",nonce_str=\"12Ddbb6gvtQrgaaEyMoAk1iSMJ73NhUa\",timestamp=\"1730106898\",serial_no=\"7363A7390A020DC1714C23F4511483FF5F49B6C4\",signature=\"mdfPiksn0pgDjuckUDRGpFcjEf+GnwWPlbjWRxoK8LhkD8x7gnLozX/8D3OyM4YOqISY6KoWWprzfZvelIN+3HfPc7JSBK7NvflJtB/LT35HJu+ih2VeLzOcRNyKxsZzQohjUKdOCrg6AylMDFaM7yo0G5gp0uuv1Un8KYwk2yGT72bl8g0tpWHzzkqK0dHTISklnedyYSzCiMFuykXetsrPrlta4zPILKQ601Dtdl8GgQaF884YwWxc6LG5YQab1qcommDKG4GWJLzGPNU+oefoDj53MPZicA+kSpxBhRTnWPN6DIOZwEcVnlAaMGC151qKK4bUK2+RZ67Ifq0coQ==\"","Accept":" */*","User-Agent":"WechatPay-Java/0.2.14 (Mac OS X/14.3) Java/21.0.2 Credential/WechatPay2Credential Validator/ okhttp3/null","Content-Type":"application/json"}}}]

**Comment by Memory-9527** [comment]
新商户不再签发平台证书，你需要使用公钥模式，不需要再调用该接口

**Comment by SpringZch** [comment]
> 新商户不再签发平台证书，你需要使用公钥模式，不需要再调用该接口

你好， 请问公钥模式是调用哪个接口呢？
