### ISSUE TITLE
新注册的商户号在请求证书时，总是报‘证书不存’

### ISSUE THREAD

**Issue by aohanhe** [wechatpay-apiv3/wechatpay-java#306]
### 错误描述

我同一个程序，当配置一个新注册的商户号就总是报错，我反复检查过商户号、证书、v3密码，都无法解决这个问题：
httpResponseBody[{"code":"RESOURCE_NOT_EXISTS","message":"证书不存在"}]	HttpRequest[{"http_method":"GET","url":"https://api.mch.weixin.qq.com/v3/certificates?algorithm_type=RSA","uri":"https://api.mch.weixin.qq.com/v3/certificates?algorithm_type=RSA"。

### 重现bug的步骤

httpResponseBody[{"code":"RESOURCE_NOT_EXISTS","message":"证书不存在"}]	HttpRequest[{"http_method":"GET","url":"https://api.mch.weixin.qq.com/v3/certificates?algorithm_type=RSA","uri":"https://api.mch.weixin.qq.com/v3/certificates?algorithm_type=RSA"

### 预期行为

正确返回结果

### 导致错误的代码片段

```Java
httpResponseBody[{"code":"RESOURCE_NOT_EXISTS","message":"证书不存在"}]	HttpRequest[{"http_method":"GET","url":"https://api.mch.weixin.qq.com/v3/certificates?algorithm_type=RSA","uri":"https://api.mch.weixin.qq.com/v3/certificates?algorithm_type=RSA"
```

### 操作系统

macos

### Java 版本

java 17

### wechatpay-java 版本

0.2.14

### 其他信息

不知道问题在那里，我都怀疑是不是微信支付平台的bug.但又没有办法找到人工技术支持

**Comment by wangg0** [comment]
据说是新注册的商户号不再提供平台证书了。所以需要使用RSAPublicKeyConfig加载本地证书。可以正常下单，但是支付回调我这边始终失败，未知原因。反正就是坑得很。官方也没有什么文档说明。

**Comment by lin-youming** [comment]
新商户只支持公钥模式了  看微信社区

**Comment by water-kid** [comment]
咋办啊，新商户报404 无可用的平台证书，请在商户平台-API安全申请使用微信支付公钥

**Comment by Eric-Lee-Handyman** [comment]
已解决，请使用最新版本 SDK
