### ISSUE TITLE
无法通过classpath加载加密文件

### ISSUE THREAD

**Issue by ylx19931228** [wechatpay-apiv3/wechatpay-java#318]
### 您的功能请求与问题有关吗？ 请描述您遇到的问题

1. 无法通过classpath加载加密文件

### 描述您想要的解决方案

通过 classpath加载加密文件，不写入固定路径

**Comment by wswdavid** [comment]
可以参考这个issue的解决方案 
https://github.com/wechatpay-apiv3/wechatpay-java/issues/198

**Comment by ylx19931228** [comment]
谢谢, 已解决.
org. springframework. core. io.Resource. 加载密钥文件.
再通过hutool 工具中的read方法,进行utf-8内容读取到privateKey 属性中.
