### ISSUE TITLE
初始化微信配置的时候报错

### ISSUE THREAD

**Issue by Heisenberg111352** [wechatpay-apiv3/wechatpay-java#326]
### 错误描述

 使用自动更新平台证书的RSA配置。项目启动的时候报错

### 重现bug的步骤

![ff398ffdd3b1d28033ae43c2c827e30](https://github.com/user-attachments/assets/dfb30397-a38c-44d6-a809-9a799c1b6a52)

### 预期行为

![微信图片_20241220122543](https://github.com/user-attachments/assets/4bdcbfb0-46e6-4062-a62d-7ba751d9643b)

### 导致错误的代码片段

```Java
// 使用自动更新平台证书的RSA配置
        // 一个商户号只能初始化一个配置，否则会因为重复的下载任务报错
        try {
            config = new RSAAutoCertificateConfig.Builder()
                    .merchantId(merchantId)
                    //.privateKeyFromPath(privateKeyPath)
                    .privateKey(getPrivateKeyPath())
                    .merchantSerialNumber(merchantSerialNumber)
                    .apiV3Key(apiV3Key)
                    .build();
        } catch (Exception e) {
            config = null;
            log.error("初始化微信配置失败", e);
        }
```

### 操作系统

linux

### Java 版本

Java 17

### wechatpay-java 版本

0.2.14

**Comment by dahaiwugui** [comment]
一样的代码，我的是报这个错误，私钥都重新生成了一遍，merchantSerialNumber是从网页上粘贴过去的还是不行，把key直接传字符串也不行

代码
private static Config config =
            new RSAAutoCertificateConfig.Builder()
                    .merchantId(merchantId)
                    // 使用 com.wechat.pay.java.core.util 中的函数从本地文件中加载商户私钥，商户私钥会用来生成请求的签名
                    .privateKey(private_key)
                    .merchantSerialNumber(merchantSerialNumber)
                    .apiV3Key(apiV3Key)
                    .build();
报错
Caused by: javax.crypto.AEADBadTagException: Tag mismatch!
        at java.base/com.sun.crypto.provider.GaloisCounterMode$GCMDecrypt.doFinal(GaloisCounterMode.java:1395)
        at java.base/com.sun.crypto.provider.GaloisCounterMode.engineDoFinal(GaloisCounterMode.java:406)
        at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2205)
        at com.wechat.pay.java.core.cipher.AbstractAeadCipher.decrypt(AbstractAeadCipher.java:78)

**Comment by jongwong** [comment]
最后解决了吗

**Comment by dahaiwugui** [comment]
已经解决了,是key的问题

jongwong ***@***.***> 于2025年2月17日周一 03:10写道：
