### ISSUE TITLE
APP下单获取PrepayId后，有接口能调起微信支付吗？

### ISSUE THREAD

**Issue by dreamozilla** [wechatpay-apiv3/wechatpay-java#33]
APP下单获取PrepayId后，有接口能调起微信支付吗？
还是说要用OpenSDK调起支付？

**Comment by xy-peng** [comment]
<img width="1584" alt="image" src="https://user-images.githubusercontent.com/1812516/187818326-475088d3-c045-4171-b08d-b06ab768841c.png">

非 SDK 的问题请直接呼叫[在线技术支持](https://support.pay.weixin.qq.com/online-service?from=github)。
