### ISSUE TITLE
请问APIV3是否支持拆单功能？以及退款的时候是否可以拆单退款？

### ISSUE THREAD

**Issue by GongZhengMe** [wechatpay-apiv3/wechatpay-java#39]
### 您的功能请求与问题有关吗？ 请描述您遇到的问题

请问APIV3是否支持拆单功能？以及退款的时候是否可以拆单退款？

### 描述您想要的解决方案

希望可以支持拆单，以及拆单的退款

**Comment by xy-peng** [comment]
不太清楚“拆单支付”具体是什么，需求的背景是什么。如果是业务解决方案的诉求，请在我们的[开发者社区](https://developers.weixin.qq.com/community/pay)反馈。

希望在GitHub，我们专注讨论 SDK。

**Comment by GongZhengMe** [comment]
> 

好的，这里主要想知道的是SDK是否支持一笔订单，可以包含多个商品。并且在退款的时候，可以根据各个商品进行分别退款。在github上的sdk文档上没有看到类似的demo或者例子

**Comment by xy-peng** [comment]
确实不支持合单支付。

对于SDK还不支持的接口，可自行组装请求和应答后 [发送 HTTP 请求](https://github.com/wechatpay-apiv3/wechatpay-java#%E5%8F%91%E9%80%81-http-%E8%AF%B7%E6%B1%82) 。

文档中，我来补充一个更完整的示例。

**Comment by xy-peng** [comment]
文档已增加 [发送 HTTP 请求](https://github.com/wechatpay-apiv3/wechatpay-java#%E5%8F%91%E9%80%81-http-%E8%AF%B7%E6%B1%82)
