### ISSUE TITLE
使用SDK，Exception in thread "main" com.wechat.pay.java.core.exception.ValidationException: Validate response failed,the WechatPay signature is incorrect.

### ISSUE THREAD

**Issue by HarryXQ** [wechatpay-apiv3/wechatpay-java#46]
### 错误描述

Exception in thread "main" com.wechat.pay.java.core.exception.ValidationException: Validate response failed,the WechatPay signature is incorrect.

### 重现bug的步骤

1、使用Demo中的例子；
2、配置好所有参数后发起：下载微信支付平台证书
3、返回签名失败错误；

### 预期行为

SDK的签名不正确

### 操作系统

windows

### Java 版本

Java 17

### wechatpay-java 版本

v0.2.0

**Comment by xy-peng** [comment]
> [微信支付平台 API 证书](https://wechatpay-api.gitbook.io/wechatpay-api-v3/ren-zheng/zheng-shu#ping-tai-zheng-shu)：由微信支付负责申请的，包含微信支付平台标识、公钥信息的证书。

验签使用微信支付的平台证书，请问是否正确的设置了？不要用商户API证书哦。

可以使用[证书下载工具](https://github.com/wechatpay-apiv3/CertificateDownloader)下载。

**Comment by HarryXQ** [comment]
换了证书后，可以使用。
那另外一个问题，小程序端请求支付对应的签名信息我怎么在后端获取？方便我下发给小程序端。
![2f7768fe4bd05f338d2a3fea5e78512](https://user-images.githubusercontent.com/76476546/195754577-2ebae07e-c1e1-413b-ac3f-e4192fa60f84.jpg)

**Comment by HarryXQ** [comment]
apiv3如何配置沙盒环境？？？？
