### ISSUE TITLE
jsapipay 前端小程序需要的签名如何生成

### ISSUE THREAD

**Issue by xulang** [wechatpay-apiv3/wechatpay-java#47]
### 您的功能请求与问题有关吗？ 请描述您遇到的问题

jsapipay 前端小程序需要的签名如何生成

**Comment by HarryXQ** [comment]
已经签名成功。 想问问 apiv3的沙盒环境如何设置？？？？

**Comment by xulang** [comment]
> 已经签名成功。 想问问 apiv3的沙盒环境如何设置？？？？

privateKey再重新构造一个吗？那个RSAConfig对象里的privateKey是私有的

**Comment by xulang** [comment]
![image](https://user-images.githubusercontent.com/8006507/195991699-cd246b2c-6f70-4575-8ece-3c2694902f37.png)

**Comment by xulang** [comment]
还是直接这样就可以了
![image](https://user-images.githubusercontent.com/8006507/195991755-a5b5e919-3b1f-44f9-98c2-726be0ee0ce8.png)

**Comment by xulang** [comment]
config对象知提供了加解密，没提供加签验签？

**Comment by nrcy** [comment]
https://pay.weixin.qq.com/wiki/doc/apiv3/wechatpay/wechatpay7_1.shtml
微信支付在一个不起眼的角落里有写，难找就是了，希望可以帮到你

**Comment by xy-peng** [comment]
> config对象知提供了加解密，没提供加签验签？

直接用商户 API 私钥 new 一个 `RSASigner`，用 `RSASigner.sign(String message)` 生成签名。

讨论请参考 #30 。

**Comment by xy-peng** [comment]
> 已经签名成功。 想问问 apiv3的沙盒环境如何设置？？？？

暂时不支持。建议在开发者社区提出你的诉求，这里仅讨论 SDK 的问题。
