### ISSUE TITLE
自动下载的证书使用场景？

### ISSUE THREAD

**Issue by xulang** [wechatpay-apiv3/wechatpay-java#48]
### 您的功能请求与问题有关吗？ 请描述您遇到的问题

自动下载的证书干嘛用的？能举个例子吗？是否还需要定期调用自动下载续期？
感觉微信支付真的是乱七八糟，这些写sdk都不知道自己有没有从头到尾接过。学习一下支付宝？

**Comment by Eric-Lee-Handyman** [comment]
您好，目前"平台证书自动下载"功能规划中，欢迎 PR。
目前，可以使用“平台证书下载工具”下载：https://github.com/wechatpay-apiv3/CertificateDownloader
