### ISSUE TITLE
验签失败

### ISSUE THREAD

**Issue by xulang** [wechatpay-apiv3/wechatpay-java#49]
### 错误描述

Validate response failed,the WechatPay signature is incorrect.
↵Request-ID[08A8AAAB9A0610D10718E8C5C05520A5B00D2880EE03-0]	responseHeader[Keep-Alive=timeout=8,Wechatpay-Timestamp=1665848617,Server=nginx,X-Content-Type-Options=nosniff,Connection=keep-alive,Date=Sat, 15 Oct 2022 15:43:37 GMT,Wechatpay-Signature-Type=WECHATPAY2-SHA256-RSA2048,Wechatpay-Serial=6A79D4EC075AD126ED5D20E925507117F5F0C8FA,Wechatpay-Nonce=0a5ccb1cfb2add2f751351f363c1ead1,Wechatpay-Signature=o+YfoCHERSItpuezH4Lgo9QotjIW/9mGoh0KSkDvPHQtAsnE8NGysDJDB4oR4LZeMTozCjpkBhvtuxkdLXghKwH5G0/V6PrqvPBtPopNpoNVlU1dDgMXWaDNng0gLqgxdEFVT4N7fWOy/NfyKDn2IFQdAIzlGdrs/xre2y5oVkUrwu54SSHUWwc0srDEGRQZA7eZS5sitJLCYozjt6UiGrbcak39iqVAP5xKojqjY1BCIqKavgNKg1JRB765IGcxQlae5nwSyVPOHBUUkbwWY+DLgd6VHkT+Crc0JimCX1B8MjWfwa3amC0lW/hpTGf0+LCI9FB1qj8AJEd0ladFhA==,Cache-Control=no-cache, must-revalidate,Content-Length=52,Request-ID=08A8AAAB9A0610D10718E8C5C05520A5B00D2880EE03-0,Content-Language=zh-CN,Content-Type=application/json; charset=utf-8↵]	responseBody[{"prepay_id":"wx15234337156985c7708abc64fd7e610000"}]"

### 重现bug的步骤

Validate response failed,the WechatPay signature is incorrect.
↵Request-ID[08A8AAAB9A0610D10718E8C5C05520A5B00D2880EE03-0]	responseHeader[Keep-Alive=timeout=8,Wechatpay-Timestamp=1665848617,Server=nginx,X-Content-Type-Options=nosniff,Connection=keep-alive,Date=Sat, 15 Oct 2022 15:43:37 GMT,Wechatpay-Signature-Type=WECHATPAY2-SHA256-RSA2048,Wechatpay-Serial=6A79D4EC075AD126ED5D20E925507117F5F0C8FA,Wechatpay-Nonce=0a5ccb1cfb2add2f751351f363c1ead1,Wechatpay-Signature=o+YfoCHERSItpuezH4Lgo9QotjIW/9mGoh0KSkDvPHQtAsnE8NGysDJDB4oR4LZeMTozCjpkBhvtuxkdLXghKwH5G0/V6PrqvPBtPopNpoNVlU1dDgMXWaDNng0gLqgxdEFVT4N7fWOy/NfyKDn2IFQdAIzlGdrs/xre2y5oVkUrwu54SSHUWwc0srDEGRQZA7eZS5sitJLCYozjt6UiGrbcak39iqVAP5xKojqjY1BCIqKavgNKg1JRB765IGcxQlae5nwSyVPOHBUUkbwWY+DLgd6VHkT+Crc0JimCX1B8MjWfwa3amC0lW/hpTGf0+LCI9FB1qj8AJEd0ladFhA==,Cache-Control=no-cache, must-revalidate,Content-Length=52,Request-ID=08A8AAAB9A0610D10718E8C5C05520A5B00D2880EE03-0,Content-Language=zh-CN,Content-Type=application/json; charset=utf-8↵]	responseBody[{"prepay_id":"wx15234337156985c7708abc64fd7e610000"}]"

### 预期行为

验签通过

### 操作系统

win10

### Java 版本

java8

### wechatpay-java 版本

0.2.0

### 其他信息

Validate response failed,the WechatPay signature is incorrect.
↵Request-ID[08A8AAAB9A0610D10718E8C5C05520A5B00D2880EE03-0]	responseHeader[Keep-Alive=timeout=8,Wechatpay-Timestamp=1665848617,Server=nginx,X-Content-Type-Options=nosniff,Connection=keep-alive,Date=Sat, 15 Oct 2022 15:43:37 GMT,Wechatpay-Signature-Type=WECHATPAY2-SHA256-RSA2048,Wechatpay-Serial=6A79D4EC075AD126ED5D20E925507117F5F0C8FA,Wechatpay-Nonce=0a5ccb1cfb2add2f751351f363c1ead1,Wechatpay-Signature=o+YfoCHERSItpuezH4Lgo9QotjIW/9mGoh0KSkDvPHQtAsnE8NGysDJDB4oR4LZeMTozCjpkBhvtuxkdLXghKwH5G0/V6PrqvPBtPopNpoNVlU1dDgMXWaDNng0gLqgxdEFVT4N7fWOy/NfyKDn2IFQdAIzlGdrs/xre2y5oVkUrwu54SSHUWwc0srDEGRQZA7eZS5sitJLCYozjt6UiGrbcak39iqVAP5xKojqjY1BCIqKavgNKg1JRB765IGcxQlae5nwSyVPOHBUUkbwWY+DLgd6VHkT+Crc0JimCX1B8MjWfwa3amC0lW/hpTGf0+LCI9FB1qj8AJEd0ladFhA==,Cache-Control=no-cache, must-revalidate,Content-Length=52,Request-ID=08A8AAAB9A0610D10718E8C5C05520A5B00D2880EE03-0,Content-Language=zh-CN,Content-Type=application/json; charset=utf-8↵]	responseBody[{"prepay_id":"wx15234337156985c7708abc64fd7e610000"}]"

**Comment by Eric-Lee-Handyman** [comment]
您好，请确认使用的平台证书是否正确，这里验签使用的是平台证书。

**Comment by Speefictor** [comment]
> 您好，请确认使用的平台证书是否正确，这里验签使用的是平台证书。

平台证书就是apiclient_cert.pem这个文件吧？我是相同的问题，用的apiclient_cert.pem这个证书，发出成功了，但是验证response失败

**Comment by xy-peng** [comment]
> 平台证书就是apiclient_cert.pem这个文件吧？我是相同的问题，用的apiclient_cert.pem这个证书，发出成功了，但是验证response失败

[微信支付平台证书](https://wechatpay-api.gitbook.io/wechatpay-api-v3/ren-zheng/zheng-shu#ping-tai-zheng-shu)：由微信支付负责申请的，包含微信支付平台标识、公钥信息的证书。首次下载平台证书可使用[微信支付 APIv3 平台证书下载工具](https://github.com/wechatpay-apiv3/CertificateDownloader)。
