### ISSUE TITLE
下载证书能默认把验签去掉吗？或者给个开关，恶心的一批

### ISSUE THREAD

**Issue by xulang** [wechatpay-apiv3/wechatpay-java#50]
### 您的功能请求与问题有关吗？ 请描述您遇到的问题

你们要是真的为安全着想，请完善sdk，让上层应用透明使用，封装都不知道吗？搞的什么玩意。
就算我第一次把证书通过jar下载下来了，配置在了配置文件（本地或者etcd）里，我更新证书的时候还要去改这他们？如果不改，一旦失效，新的证书就下载不下来了。而且你们提供的默认下载在内存里，重启后不还是老证书在验签，总有一天他们会不能用，不是嘛。

### 描述您想要的解决方案

证书完全内存化，对上层业务透明，第一次下载证书无需验证。
就像https协议一样，请sdk自行实现续约，不要垃圾搞一半，拿出点水准来？

**Comment by Eric-Lee-Handyman** [comment]
您好，可以参考这个issue解决您的问题：https://github.com/wechatpay-apiv3/wechatpay-java/issues/27
“平台证书自动下载”功能规划中，欢迎 PR。

**Comment by Gradually** [comment]
https://github.com/wechatpay-apiv3/wechatpay-apache-httpclient
微信支付这个SDK又支持不验签下载，搞得好像两个团队开发一样- -。

**Comment by Eric-Lee-Handyman** [comment]
> 

您好，您发的是我们之前开发的apache httpclient扩展。
新版本的SDK尚未支持“平台证书自动下载”功能，目前正在规划中，欢迎 PR。
