### ISSUE TITLE
V3版本的POST无参数请求会一直报错

### ISSUE THREAD

**Issue by Will-yc** [wechatpay-apiv3/wechatpay-java#59]
### 错误描述

解约接口：/v3/offlinefacemch/organizations/{organization_id}/users/user-id/{user_id}/terminate-contract，文档要求不需要参数，参考文档，使用api中的httpClient请求是一直提示`请求的参数错误`，其他接口请求都正常，唯独这个无参的POST请求不同，接口参考地址：https://pay.weixin.qq.com/wiki/doc/wxfacepay/develop/k12-development-guidelines.html#_4-6-%E8%A7%A3%E9%99%A4%E5%88%B7%E8%84%B8%E7%94%A8%E6%88%B7%E7%AD%BE%E7%BA%A6%E5%85%B3%E7%B3%BB%E6%8E%A5%E5%8F%A3

### 重现bug的步骤

![image](https://user-images.githubusercontent.com/21304095/201453142-171742f1-d781-4e8f-b623-a62f5fd7b385.png)
这个是代码，参数为空，一直提示参数有误

### 预期行为

正常执行接口请求

### 操作系统

windows

### Java 版本

java11

### wechatpay-java 版本

0.2.0

**Comment by xy-peng** [comment]
看起来是服务端报错了。你试试不设置body的值为 `{}` ？

**Comment by Will-yc** [comment]
![image](https://user-images.githubusercontent.com/21304095/201465452-f48f7e22-f53f-46e9-b7da-6fe4d74348d1.png)
依然是请求参数错误

**Comment by Will-yc** [comment]
organization_id 和 user_id的值是没有问题的，因为是从上一个业务直接复制过来的

**Comment by Will-yc** [comment]
无论怎么传值，都会报错，这个问题应该向那里提出，搞的现在业务进行不下去了

**Comment by xy-peng** [comment]
1. 检查下 user-id 是否正确
2. 检查下是否已经解绑或者绑定关系不存在

我估计这个API输出的错误消息不准确，所以你无法定位到问题。建议你参考我说的两点检查检查。

业务问题可以在开放平台社区发帖，或者联系[在线技术支持](https://support.pay.weixin.qq.com/online-service?from=github)。
