### ISSUE TITLE
wechatpay-java 调用nativePay支付接口报错

### ISSUE THREAD

**Issue by xl277541808** [wechatpay-apiv3/wechatpay-java#60]
### 错误描述

我用的版本是：
![image](https://user-images.githubusercontent.com/37787244/201571868-f70232c1-e84d-4ced-bb3a-8f6fb0e07bba.png)
调用的接口是：
![image](https://user-images.githubusercontent.com/37787244/201572071-ab14b010-3650-424b-8b9e-fe5bfae3d842.png)
我跟进去看了是：
![image](https://user-images.githubusercontent.com/37787244/202343090-e1d29ab6-8ba4-4b07-b6c1-2378eeac9c1b.png)
![image](https://user-images.githubusercontent.com/37787244/202343151-8cd1a539-2395-410c-a056-cf8fc3fd3f0b.png)
看起来参数的顺序都不对。
请问，我的是不是不是最新版本的wechatpay-java呀？
![image](https://user-images.githubusercontent.com/37787244/201572484-b2ae3c22-70d5-4e8b-ac18-3a04dc181755.png)
现在该怎么办呢？

### 重现bug的步骤

如上

### 预期行为

如上

### 操作系统

windows

### Java 版本

java 17

### wechatpay-java 版本

0.2.0

### 其他信息

如上

**Comment by xy-peng** [comment]
wechatpay-java 依赖的是 OkHttp 4.x，你项目中引入的是 3.x。

建议谨慎地升级，参考[adding-constraints-transitive-deps](https://docs.gradle.org/current/userguide/dependency_constraints.html#sec:adding-constraints-transitive-deps) 指定 OkHttp 4.x 版本。按照 [OkHttp 官方的迁移指南](https://square.github.io/okhttp/changelogs/upgrading_to_okhttp_4/)，OkHttp 4.x 是向下兼容 OkHttp 3.x。

希望收到你兼容性的报告。

**Comment by xl277541808** [comment]
可是我是直接引的jar包呀，
![image](https://user-images.githubusercontent.com/37787244/201582087-c1809173-06c6-4cbc-8852-26503dcf623e.png)
<dependency>
			<groupId>com.github.wechatpay-apiv3</groupId>
			<artifactId>wechatpay-java</artifactId>
			<version>0.2.0</version>
</dependency>
意思是这个打好的jar里面引用错了，需要我自己去引OkHttp 4.x 版本？

**Comment by xy-peng** [comment]
猜测是你在项目主动依赖了 `OkHttp 3.x` 或者依赖的其他组件依赖了。你用 IDE 或者 gradle 查看下项目的依赖就知道了。

也可以参考下其他项目 [类似问题的指引](https://github.com/wechatpay-apiv3/wechatpay-apache-httpclient#%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3jackson-nosuchmethoderror%E6%8A%A5%E9%94%99)。

**Comment by zijianrs** [comment]
@xl277541808 我跟你遇到了一样的问题 按照如下所示修改pom文件得以解决
```xml
        <dependency>
            <groupId>com.github.wechatpay-apiv3</groupId>
            <artifactId>wechatpay-java</artifactId>
            <version>0.2.1</version>
            <exclusions>
                <exclusion>
                    <artifactId>okhttp</artifactId>
                    <groupId>com.squareup.okhttp3</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>4.10.0</version>
        </dependency>
```
@xy-peng 我查看了下依赖树 发现 wechatpay-java-core 引入的 okhttp 版本是 3.14.9 如下图所示
![image](https://user-images.githubusercontent.com/89035011/202290816-62380eed-1ba8-4778-aad3-21aa114f8304.png)

**Comment by xl277541808** [comment]
> @xl277541808 我跟你遇到了一样的问题 按照如下所示修改 pom 文件得以解决
> 
> ```
>         <dependency>
>             <groupId>com.github.wechatpay-apiv3</groupId>
>             <artifactId>wechatpay-java</artifactId>
>             <version>0.2.1</version>
>             <exclusions>
>                 <exclusion>
>                     <artifactId>okhttp</artifactId>
>                     <groupId>com.squareup.okhttp3</groupId>
>                 </exclusion>
>             </exclusions>
>         </dependency>
>         <dependency>
>             <groupId>com.squareup.okhttp3</groupId>
>             <artifactId>okhttp</artifactId>
>             <version>4.10.0</version>
>         </dependency>
> ```
> 
> @xy-peng 我查看了下依赖树 发现 wechatpay-java-core 引入的 okhttp 版本是 3.14.9 如下图所示 ![image](https://user-images.githubusercontent.com/89035011/202290816-62380eed-1ba8-4778-aad3-21aa114f8304.png)
-----------------------------------------------------------------------------------------------------------------------------
@zijianrs 
大佬，我按照你说的试过。原本是这样， wechatpay-java-core 自身内部依赖的是okhttp  3.14.9
![image](https://user-images.githubusercontent.com/37787244/202332183-4c770179-7ba8-4ed7-b00d-e8f2c62f37c0.png)
然后，改了之后：
![image](https://user-images.githubusercontent.com/37787244/202332601-19d16001-c406-4abb-bf3b-867d20b23da1.png)
运行报错，提示同样的问题
![image](https://user-images.githubusercontent.com/37787244/202340265-a9fcaf0b-4ff3-41cd-9a3c-5a8230f518be.png)

**Comment by xl277541808** [comment]
@zijianrs 
后来，为了赶时间，没有研究了。用了另一种方式：wechatpay-apache-httpclient
![image](https://user-images.githubusercontent.com/37787244/202341427-d3b27d3b-7c02-4f69-801e-50ec9693dbb0.png)
这个感觉挺简单的。拿进来就能用了，
![image](https://user-images.githubusercontent.com/37787244/202341550-636b11d2-6257-4fff-83e2-90295838cd97.png)
然后是调用接口，二维码地址一下就出来了
![image](https://user-images.githubusercontent.com/37787244/202342067-5625a3d9-3885-4f7a-ba83-2a64c940fb11.png)
我猜，是不是环境不一样。我是在spring-boot api 里面使用的
