### ISSUE TITLE
业务接口和使用实例中没有找到商家转账到零钱的服务

### ISSUE THREAD

**Issue by lyusantu** [wechatpay-apiv3/wechatpay-java#61]
### 您的功能请求与问题有关吗？ 请描述您遇到的问题

文档地址：https://pay.weixin.qq.com/wiki/doc/apiv3/apis/chapter4_3_1.shtml

### 描述您想要的解决方案

提供商家转账号零钱的服务Demo

**Comment by xy-peng** [comment]
暂时没有。已经在计划中。

**Comment by SuuuperLyb** [comment]
建议开发文档标记一下

**Comment by xy-peng** [comment]
在 v0.2.2 中已支持
