### ISSUE TITLE
使用DefaultHttpClientBuilder构造出来的HttpClient需要关闭吗？

### ISSUE THREAD

**Issue by sxshunrj** [wechatpay-apiv3/wechatpay-java#62]
### 您的功能请求与问题有关吗？ 请描述您遇到的问题

请问使用以下代码获取的HttpClient实例需要触发关闭吗？我看这个HttpClient接口里没有close方法呢？

> Config config = new RSAConfig.Builder()
      .merchantId(merchantId)
                        .privateKeyFromPath(privateKeyPath)
                        .merchantSerialNumber(merchantSerialNumber)
                        .wechatPayCertificatesFromPath(wechatPayCertificatePath)
                        .build();

> HttpClient httpClient = new DefaultHttpClientBuilder()
        .readTimeoutMs(3000)
        .writeTimeoutMs(3000)
        .connectTimeoutMs(3000)
        .credential(requireNonNull(config.createCredential()))
        .validator(requireNonNull(config.createValidator()))
        .build();

maven依赖如下：
![image](https://user-images.githubusercontent.com/18591209/202140246-64fc7565-2099-4250-9354-b5187349e1b1.png)

### 描述您想要的解决方案

-

### 您还有其他的方案吗？

-

### 其他信息

-

**Comment by lianup** [comment]
不需要。当前构造出来的`HttpClient`底层会持有一个`OkHttpClient`，在每一次请求返回时，将调用`okHttpResponse.body.string()`获取返回body并释放资源，`OkHttpClient`会保持连接直到超时关闭。
如果有需要主动触发关闭的场景，请描述下。

**Comment by sxshunrj** [comment]
> 不需要。当前构造出来的`HttpClient`底层会持有一个`OkHttpClient`，在每一次请求返回时，将调用`okHttpResponse.body.string()`获取返回body并释放资源，`OkHttpClient`会保持连接直到超时关闭。 如果有需要主动触发关闭的场景，请描述下。

好的，明白了，多谢啦
