### ISSUE TITLE
NotificationParser类第92行，异常提示值不匹配问题

### ISSUE THREAD

**Issue by ZCYF** [wechatpay-apiv3/wechatpay-java#65]
### 错误描述

![image](https://user-images.githubusercontent.com/33826351/202381290-a683ed10-01e5-4acd-9414-e1abad573338.png)

NotificationParser类第92行，异常提示值不匹配问题

### 重现bug的步骤

控制台排查问题不友好

### 预期行为

友好查看异常信息

### 导致错误的代码片段

```Java
![image](https://user-images.githubusercontent.com/33826351/202381290-a683ed10-01e5-4acd-9414-e1abad573338.png)
```

### 操作系统

windows

### Java 版本

java8

### wechatpay-java 版本

0.2.1

**Comment by lianup** [comment]
感谢指正，我来改下。
