### ISSUE TITLE
微信收款商业版的订单如何查询

### ISSUE THREAD

**Issue by KingCesc** [wechatpay-apiv3/wechatpay-java#67]
### 如图所示，这种订单无法查询。
![image](https://user-images.githubusercontent.com/6245152/203018324-8a220dd7-4c81-47bf-ba7f-b1f2523a7100.png)

### 使用的是NativePayService
    /**
     * 微信支付订单号查询订单
     */
    public static Transaction queryOrderById() {

        QueryOrderByIdRequest request = new QueryOrderByIdRequest();
        // 调用request.setXxx(val)设置所需参数，具体参数可见Request定义
        // 调用接口
        request.setSpMchid("");
        request.setSubMchid("");
        request.setTransactionId("");
        return service.queryOrderById(request);
    }

### 请求返回
{"code":"PARAM_ERROR","message":"普通商户不允许传sub_mch_id"}

**Comment by xy-peng** [comment]
如果你用的是服务商对应的 [partnerpayments](https://github.com/wechatpay-apiv3/wechatpay-java/tree/main/service/src/main/java/com/wechat/pay/java/service/partnerpayments) ，是不是发送请求用的不是服务商商户号？初始化时传入的应是服务商的商户号、API私钥等。

**Comment by KingCesc** [comment]
- 使用的是partnerpayments 

- request.setSpMchid("");  这里使用的是我的商户号，
![image](https://user-images.githubusercontent.com/6245152/203189904-03bf17f0-84f0-412a-b0d0-c1354aec5492.png)


- request.setSubMchid("");  这里使用的微信收款商业版的商户号
![image](https://user-images.githubusercontent.com/6245152/203189951-1e8493d8-fa9f-4129-808f-50965430acb4.png)


- 另外我在论坛查到，以前是不支持api查询微信收款商业版的订单，不知道现在政策有无变化？
![image](https://user-images.githubusercontent.com/6245152/203190043-6ae5d188-02d4-48d5-8cb2-e16c6ae3a44c.png)

**Comment by xy-peng** [comment]
原来是具体业务的问题，请以技术支持的回答为准。
