### ISSUE TITLE
createOkHttpRequestBody 异常

### ISSUE THREAD

**Issue by chengling235** [wechatpay-apiv3/wechatpay-java#78]
### 错误描述

java.lang.NoSuchMethodError: okhttp3.RequestBody.create(Ljava/lang/String;Lokhttp3/MediaType;)Lokhttp3/RequestBody;

### 重现bug的步骤

createOkHttpRequestBody 异常

### 预期行为

createOkHttpRequestBody 异常

### 操作系统

macos

### Java 版本

java 8

### wechatpay-java 版本

0.2.1

**Comment by lianup** [comment]
请先参考 #70

**Comment by xy-peng** [comment]
在 v0.2.2 中做了兼容 @chengling235
