### ISSUE TITLE
什么时候可以使用呢

### ISSUE THREAD

**Issue by seiyap70** [wechatpay-apiv3/wechatpay-java#8]
这个java sdk 什么时候可以使用呢，发布版本

**Comment by Eric-Lee-Handyman** [comment]
目前在商户试点阶段，欢迎试用，一起完善~

**Comment by seiyap70** [comment]
> 目前在商户试点阶段，欢迎试用，一起完善~

需要我自己下代码打包吗

**Comment by Eric-Lee-Handyman** [comment]
可以先自行打包 JAR 文件引入。
等项目稳定后，我们再放到maven repository上。

**Comment by seiyap70** [comment]
> 可以先自行打包 JAR 文件引入。 等项目稳定后，我们再放到maven repository上。

有时间计划吗，大概还要多久呢

**Comment by Eric-Lee-Handyman** [comment]
目前时间未定，要看商户侧试用情况及后续我们的改造工作量。
