### ISSUE TITLE
Validate response failed,the WechatPay signature is incorrect.

### ISSUE THREAD

**Issue by yuandoudou928** [wechatpay-apiv3/wechatpay-java#84]
### 错误描述

我使用 JsapiServiceExtensionExample 中的代码，提示：Validate response failed,the WechatPay signature is incorrect.
代码中有句注释：
// 使用 com.wechat.pay.java.core.util 中的函数从本地文件中加载商户私钥，商户私钥会用来生成请求的签名
                .privateKeyFromPath()
但是：privateKeyFromPath() 方法的参数是 String，私钥的路径。而 PemUtil 工具类的方法，是加载私钥。这是什么意思？重复了？

### 重现bug的步骤

1.直接用你们的代码就能复现

### 预期行为

至少用你们的示例代码能下单吧

### 导致错误的代码片段

```Java
// 初始化商户配置
    RSAConfig config =
        new RSAConfig.Builder()
            .merchantId(merchantId)
            // 使用 com.wechat.pay.java.core.util 中的函数从本地文件中加载商户私钥，商户私钥会用来生成请求的签名
            .privateKeyFromPath(privateKeyPath)
            .merchantSerialNumber(merchantSerialNumber)
            .wechatPayCertificatesFromPath(wechatPayCertificatePath)
            .build();
```

### 操作系统

macOS

### Java 版本

java1.8

### wechatpay-java 版本

0.2.2

### 其他信息

用SDK，不是不用自己签名吗？

**Comment by miao5371** [comment]
![image](https://user-images.githubusercontent.com/63583569/208394555-6eb512ad-a6af-4acc-bd65-380fd7a2cf87.png)
提供的测试方法报错，结果都返回了，然后在返回头的验证中报错。

**Comment by xy-peng** [comment]
`wechatPayCertificatesFromPath` 应该传入的是[微信支付平台证书](https://wechatpay-api.gitbook.io/wechatpay-api-v3/ren-zheng/zheng-shu#ping-tai-zheng-shu)的路径，你是不是用了自己的商户证书？
