### ISSUE TITLE
商家转账到零钱，如果超出免密额度，出资商户在商家助手进行付款确认后，有机制通知到商家后端吗？

### ISSUE THREAD

**Issue by sxshunrj** [wechatpay-apiv3/wechatpay-java#86]
### 您的功能请求与问题有关吗？ 请描述您遇到的问题

在调用【通过商家批次单号查询批次单】接口时发现返回值里的batch_status字段有一个【WAIT_PAY】值，说明是“需要付款出资商户在商家助手小程序或服务商助手小程序进行付款确认”，但是这个确认的动作是线下的，一般也是老板或者领导进行确认，作为技术人员无法确定这个时间，就无法再在某个时间点再次触发查询批次单状态了。

### 描述您想要的解决方案

能否在出资商户进行付款确认后，主动通知一下商户后端，这样就可以再次查询批次单状态进而进行后续的业务逻辑处理了。

**Comment by xy-peng** [comment]
感谢建议。

不过，业务方面的问题请到我们的[开发者社区](https://support.pay.weixin.qq.com/online-service?from=github)反馈。在 issue 中仅讨论跟 SDK 有关的问题。谢谢配合。
