### ISSUE TITLE
我拉了最新的版本缺少类 RSAAutoCertificateConfig

### ISSUE THREAD

**Issue by ZaiHer21** [wechatpay-apiv3/wechatpay-java#88]
### 错误描述

我拉了最新的版本缺少类 RSAAutoCertificateConfig

### 重现bug的步骤

![image](https://user-images.githubusercontent.com/99528059/209103896-a55d0d9f-da79-48e0-9aea-19dd32990deb.png)
![Uploading image.png…]()

### 预期行为

直接maven下载就行

### 操作系统

macos

### Java 版本

1.8

### wechatpay-java 版本

0.2.2

**Comment by ayrtck** [comment]
我也是，maven仓库的jar还没更新

**Comment by xy-peng** [comment]
已经发布了，你们试用下。有问题欢迎反馈。
