### ISSUE TITLE
sdk中的接口与官方文档的接口不符

### ISSUE THREAD

**Issue by lanmo** [wechatpay-apiv3/wechatpay-java#90]
### 您的功能请求与问题有关吗？ 请描述您遇到的问题

https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=9_1 这个是jsapi的接口文档
这个是sdk 中的https://api.mch.weixin.qq.com/v3/pay/transactions/jsapi 接口，这个在官方文档中都没搜到这个接口
<dependency>
            <groupId>com.github.wechatpay-apiv3</groupId>
            <artifactId>wechatpay-java</artifactId>
            <version>0.2.2</version>
        </dependency>

### 描述您想要的解决方案

与官方的接口文档对齐

**Comment by xy-peng** [comment]
SDK 配套的 API 请见 [微信支付的文档中心](https://pay.weixin.qq.com/wiki/doc/apiv3/index.shtml)。
