### ISSUE TITLE
能把完整使用案例或者使用说明完善一下？？？？

### ISSUE THREAD

**Issue by 7019492** [wechatpay-apiv3/wechatpay-java#91]

**Comment by 7019492** [comment]
啊？

**Comment by xy-peng** [comment]
能更具体的说下，你是哪里遇到了困难了吗？

**Comment by liuxu713404800** [comment]
想要一个比较完整的demo，比如回调时从HttpServletRequest如何获得相关参数，如何构造RequestParam和NotificationConfig。我认为一个比较好的demo就是基本上copy完成一份代码之后，修改配置即可用，现在的话仍需东拼西凑才能获得一个可用的调用过程，体验较差

**Comment by liuxu713404800** [comment]
想要一个比较完整的demo，比如回调时从HttpServletRequest如何获得相关参数，如何构造RequestParam和NotificationConfig。我认为一个比较好的demo就是基本上copy完成一份代码之后，修改配置即可用，现在的话仍需东拼西凑才能获得一个可用的调用过程，体验较差
