### ISSUE TITLE
没人发现 RSAAutoCertificateConfig AutoCertificateNotificationConfig一起用 就会失败？

### ISSUE THREAD

**Issue by nginx-1** [wechatpay-apiv3/wechatpay-java#92]
### 错误描述

同时使用RSAAutoCertificateConfig. AutoCertificateNotificationConfig
出现异常： The corresponding provider for the merchant already exists.

### 重现bug的步骤

如上

### 预期行为

不抱错

### 操作系统

macOs

### Java 版本

Java 19

### wechatpay-java 版本

0.2.3

**Comment by tanxiuguang** [comment]
RSAAutoCertificateConfig只能作为单例用吗？第二次初始化就报错The corresponding provider for the merchant already exists.

**Comment by xy-peng** [comment]
@nginx-1 目前是的，你能详细描述下你是什么情况下需要同时使用这两者吗？我们期望商户能分离系统中处理通知回调的服务和处理支付请求的服务。

改进计划上，我们准备把 `RSAAutoCertificateConfig` 也实现 `NotificationConfig`，这样两个场景用一个配置实例就可以了。

**Comment by xy-peng** [comment]
> RSAAutoCertificateConfig只能作为单例用吗？第二次初始化就报错The corresponding provider for the merchant already exists.

@tanxiuguang 是的，只能有一个示例，你是什么场景要多次初始化？

**Comment by tanxiuguang** [comment]
> > RSAAutoCertificateConfig只能作为单例用吗？第二次初始化就报错The corresponding provider for the merchant already exists.
> 
> @tanxiuguang 是的，只能有一个示例，你是什么场景要多次初始化？

我看文档以为每次都要初始化config，理解错了。

**Comment by nginx-1** [comment]
我是一个服务，同时处理支付跟回调，没法重新构造一个config。只能通过builder 是否可以解决这个问题，请问下一个发布周期是多久 我好同步更新一下，谢谢 辛苦了

**Comment by guantou** [comment]
官方更新好快
我当时是定义一个RSAAutoCertificateProvider， 然后单独定义了AbstractRSAConfig 和 AbstractNotificationConfig的两个实现类，支持传入RSAAutoCertificateProvider。
