### ISSUE TITLE
预支付自动更新平台证书 解密失败

### ISSUE THREAD

**Issue by dangpf** [wechatpay-apiv3/wechatpay-java#93]
### 错误描述

预支付自动更新平台证书 解密失败
![微信图片_20221227123210](https://user-images.githubusercontent.com/13655991/209611414-6209a1f9-9166-4981-8e1f-6e5c0b14c92b.png)

### 重现bug的步骤

预支付自动更新平台证书 解密失败

### 预期行为

预支付自动更新平台证书 解密失败

### 操作系统

windows

### Java 版本

Java1.8.0_221

### wechatpay-java 版本

master分支

**Comment by xy-peng** [comment]
你的 apiv3key 正确吗？看日志是用 apiv3key 解密失败了

**Comment by dangpf** [comment]
> 你的 apiv3key 正确吗？看日志是用 apiv3key 解密失败了

好的，我们检查核对下，相关信息都是其他方提供的，谢谢
