### ISSUE TITLE
微信小程序支付，回调通知，官方提供api和示例有出入

### ISSUE THREAD

**Issue by xingwenkai** [wechatpay-apiv3/wechatpay-java#95]
### 错误描述

微信小程序支付，回调通知，官方提供api和示例有出入

### 重现bug的步骤

1. 这是你们的示例
![微信图片_20221228170016](https://user-images.githubusercontent.com/61527421/209786723-0ad9d820-9c8f-4d23-828a-1ad3b7a0a451.png)
2. 这是代码中要传的参数
![微信图片_20221228170146](https://user-images.githubusercontent.com/61527421/209786801-fbea28c6-b03d-42eb-9983-8ae19f4642b0.png)

这两个根本对不上呀，是两个类，你看看我需要在NotificationParser的构造方法中传什么参数？

### 预期行为

看看我需要在NotificationParser的构造方法中传什么参数？

### 操作系统

win

### Java 版本

8

### wechatpay-java 版本

0.2.3

**Comment by xy-peng** [comment]
稍安勿躁，maven还未发布

**Comment by xingwenkai** [comment]
麻烦先给我个解决方案吧

**Comment by xy-peng** [comment]
已经发布了 @xingwenkai

**Comment by xingwenkai** [comment]
仓库中没有这个jar呀，是还在发布中吗
![image](https://user-images.githubusercontent.com/61527421/209889700-5dba7f99-276e-4abc-8bcc-b2f012e54023.png)

**Comment by xingwenkai** [comment]
@xy-peng

**Comment by itunic** [comment]
版本是0.2.4，问题依旧在。

**Comment by itunic** [comment]
<img width="1368" alt="image" src="https://user-images.githubusercontent.com/23350236/210812127-71128e4c-76ee-44f2-bac8-62b475500f84.png">

**Comment by xingwenkai** [comment]
![image](https://user-images.githubusercontent.com/61527421/210908305-dd95edb4-ec3e-4f03-9cb1-fc7c829a5bf8.png)
@itunic
