### ISSUE TITLE
商户号初始化配置重复，下载任务报错。

### ISSUE THREAD

**Issue by 625609414** [wechatpay-apiv3/wechatpay-java#98]
### 错误描述

![image](https://user-images.githubusercontent.com/44861636/209823408-ec0eaa88-e471-402c-b20c-8a2a4e00e95b.png)
![image](https://user-images.githubusercontent.com/44861636/209823535-96ac01d9-b7bf-4df4-af58-cdd929c8ab97.png)
商户号初始化配置重复，下载任务报错。

### 重现bug的步骤

启动项目测试初始化配置后，重复下载任务报错问题怎么解决，还没有存到redis中。现在生成不了配置了。

### 预期行为

正常初始化商户号配置

### 导致错误的代码片段

```Java
Config config =
        new RSAAutoCertificateConfig.Builder()
            .merchantId(merchantId)
            .privateKeyFromPath(privateKeyPath)
            .merchantSerialNumber(merchantSerialNumber)
            .apiV3Key(apiV3key)
            .build();
```

### 操作系统

window

### Java 版本

java 8

### wechatpay-java 版本

v0.2.3

**Comment by xy-peng** [comment]
设计就是只能有一个自动下载微信支付平台证书的配置。

看代码不知道你是怎么做的，将它作为全局变量或者单例试试

**Comment by 625609414** [comment]
> 设计就是只能有一个自动下载微信支付平台证书的配置。
> 
> 看代码不知道你是怎么做的，将它作为全局变量或者单例试试

我已经用了单例了，只是测试接口的时候初始化了商户号配置，程序终止了后，我又启动了想再测试一次，它就报商户配置已初始化，无法初始化的错误。但是程序重启了，我一直就获取不到配置了

**Comment by deyun93** [comment]
我也出现类似情况

**Comment by xy-peng** [comment]
`RSAAutoCertificateConfig` 是不能重复配置，只能有一个实例的。

能否提供更详细的信息 @deyun93 ，无法判断你所说的是什么状况和具体原因。

**Comment by 625609414** [comment]
> `RSAAutoCertificateConfig` 是不能重复配置，只能有一个实例的。
> 
> 能否提供更详细的信息 @deyun93 ，无法判断你所说的是什么状况和具体原因。

![image](https://user-images.githubusercontent.com/44861636/210327153-1ce6cf79-5690-4ab1-be9a-f1806ec5952d.png)
你好，这里用了单例，但是现在我的问题是：我启动项目生成了商户号配置，测试接口也成功了。但是我重启了项目，又需要下载商户号配置，他就会提示我已经初始化了配置。

**Comment by deyun93** [comment]
> 你可以试试。

目前自己修改了一下代码可以用了，你给的方法我也试试，比我写得优雅一点，谢谢
